### ISSUE TITLE
plant mitochondria assembly

### ISSUE THREAD

**Issue by pollend** [Kinggerm/GetOrganelle#17]
I'm trying to do a mitochondrion assembly for and I get this error when I try to run the assembly. Looks like something Is missing. 

```
get_organelle_from_reads.py -1 ./HA2_USD16090441L_HJM35DSXX_L1_1.fq.gz ./HA2_USD16090441L_HKGF3DSXX_L4_1.fq.gz -2 ./HA2_USD16090441L_HJM35DSXX_L1_2.fq.gz ./HA2_USD16090441L_HKGF3DSXX_L4_2.fq.gz -F embplant_mt -R 50 --memory-save -k 21,45,65,85,105 -s ./mitochondrion.fasta -o mitochondrion

2019-07-12 14:54:02,625 - INFO: Pre-reading fastq ...
2019-07-12 14:54:02,625 - INFO: Estimating reads to use ...
2019-07-12 14:54:03,843 - INFO: Tasting 100000+100000 reads ...
2019-07-12 14:54:16,019 - INFO: Estimating reads to use finished.
2019-07-12 14:54:16,020 - INFO: Unzipping reads file: ./HA2_USD16090441L_HJM35DSXX_L1_1.fq.gz (8906254650 bytes)
2019-07-12 14:54:32,878 - INFO: Unzipping reads file: ./HA2_USD16090441L_HJM35DSXX_L1_2.fq.gz (9090975867 bytes)
2019-07-12 14:54:57,295 - INFO: Counting read qualities ...
2019-07-12 14:54:57,766 - INFO: Identified quality encoding format = Sanger
2019-07-12 14:54:57,768 - INFO: Trimming bases with qualities (0.00%): 33..33  !
2019-07-12 14:54:57,813 - INFO: Mean error rate = 0.0018
2019-07-12 14:54:57,815 - INFO: Counting read lengths ...
2019-07-12 14:55:18,019 - INFO: Mean = 150.0 bp, maximum = 150 bp.
2019-07-12 14:55:18,019 - INFO: Reads used = 3153321+3153321
2019-07-12 14:55:18,019 - INFO: Pre-reading fastq finished.

2019-07-12 14:55:18,019 - INFO: Making seed reads ...
2019-07-12 14:55:18,055 - INFO: Making seed - bowtie2 index ...
2019-07-12 14:55:18,687 - INFO: Making seed - bowtie2 index finished.
2019-07-12 14:55:18,688 - INFO: Mapping reads to seed bowtie2 index ...
2019-07-12 14:57:02,386 - INFO: Mapping finished.
2019-07-12 14:57:02,387 - INFO: Seed reads made: /embplant_mt.initial.fq (129010568 bytes)
2019-07-12 14:57:02,388 - INFO: Making seed reads finished.

2019-07-12 14:57:02,388 - INFO: Checking seed reads and parameters ...
2019-07-12 14:57:02,388 - INFO: The automatically-estimated parameter(s) do not ensure the best choice(s).
2019-07-12 14:57:02,388 - INFO: If the result graph is not a circular organelle genome, 
2019-07-12 14:57:02,388 - INFO:   you could adjust the value(s) of '-w'/'-R' for another new run.
2019-07-12 14:57:20,568 - INFO: Pre-assembling mapped reads ...
2019-07-12 14:57:51,703 - INFO: Pre-assembling mapped reads finished.
2019-07-12 14:57:51,704 - INFO: Estimated embplant_mt-hitting base-coverage = 168.78
2019-07-12 14:57:51,704 - INFO: Estimated word size(s): 98
2019-07-12 14:57:51,704 - INFO: Setting '-w 98'
2019-07-12 14:57:51,704 - INFO: Setting '--max-extending-len inf'
2019-07-12 14:57:52,336 - INFO: Checking seed reads and parameters finished.

2019-07-12 14:57:52,336 - INFO: Making read index ...
2019-07-12 14:58:52,684 - INFO: Mem 0.894 G, 6306642 reads
2019-07-12 14:58:53,117 - INFO: Making read index finished.

2019-07-12 14:58:53,117 - INFO: Extending ...
2019-07-12 14:58:53,117 - INFO: Adding initial words ...
2019-07-12 14:59:06,114 - INFO: AW 2048470
2019-07-12 15:00:07,250 - INFO: Round 1: 6306642/6306642 AI 726541 AW 2849312 Mem 0.828
2019-07-12 15:00:50,445 - INFO: Round 2: 6306642/6306642 AI 923061 AW 3246804 Mem 0.892
2019-07-12 15:01:28,567 - INFO: Round 3: 6306642/6306642 AI 947102 AW 3328798 Mem 0.905
2019-07-12 15:02:07,417 - INFO: Round 4: 6306642/6306642 AI 949553 AW 3352248 Mem 0.91
2019-07-12 15:02:45,246 - INFO: Round 5: 6306642/6306642 AI 951483 AW 3370990 Mem 0.915
2019-07-12 15:03:23,420 - INFO: Round 6: 6306642/6306642 AI 953243 AW 3395850 Mem 0.92
2019-07-12 15:04:03,927 - INFO: Round 7: 6306642/6306642 AI 954602 AW 3418200 Mem 0.925
2019-07-12 15:04:42,263 - INFO: Round 8: 6306642/6306642 AI 955506 AW 3433110 Mem 0.931
2019-07-12 15:05:20,903 - INFO: Round 9: 6306642/6306642 AI 956279 AW 3444530 Mem 0.934
2019-07-12 15:05:59,563 - INFO: Round 10: 6306642/6306642 AI 956835 AW 3452146 Mem 0.935
2019-07-12 15:06:38,805 - INFO: Round 11: 6306642/6306642 AI 957266 AW 3457160 Mem 0.936
2019-07-12 15:07:17,549 - INFO: Round 12: 6306642/6306642 AI 957579 AW 3460940 Mem 0.937
2019-07-12 15:07:56,990 - INFO: Round 13: 6306642/6306642 AI 957933 AW 3465170 Mem 0.939
2019-07-12 15:08:39,075 - INFO: Round 14: 6306642/6306642 AI 958284 AW 3468770 Mem 0.94
2019-07-12 15:09:18,349 - INFO: Round 15: 6306642/6306642 AI 958574 AW 3472920 Mem 0.94
2019-07-12 15:09:57,361 - INFO: Round 16: 6306642/6306642 AI 959026 AW 3477170 Mem 0.941
2019-07-12 15:10:35,997 - INFO: Round 17: 6306642/6306642 AI 959426 AW 3481418 Mem 0.941
2019-07-12 15:11:14,720 - INFO: Round 18: 6306642/6306642 AI 959672 AW 3484480 Mem 0.942
2019-07-12 15:11:52,489 - INFO: Round 19: 6306642/6306642 AI 960058 AW 3488320 Mem 0.942
2019-07-12 15:12:30,319 - INFO: Round 20: 6306642/6306642 AI 960393 AW 3491828 Mem 0.943
2019-07-12 15:13:08,071 - INFO: Round 21: 6306642/6306642 AI 960715 AW 3495002 Mem 0.943
2019-07-12 15:13:48,359 - INFO: Round 22: 6306642/6306642 AI 961006 AW 3497694 Mem 0.944
2019-07-12 15:14:27,287 - INFO: Round 23: 6306642/6306642 AI 961224 AW 3499986 Mem 0.944
2019-07-12 15:15:06,349 - INFO: Round 24: 6306642/6306642 AI 961404 AW 3501324 Mem 0.944
2019-07-12 15:15:45,252 - INFO: Round 25: 6306642/6306642 AI 961497 AW 3502046 Mem 0.945
2019-07-12 15:16:24,195 - INFO: Round 26: 6306642/6306642 AI 961521 AW 3502320 Mem 0.945
2019-07-12 15:17:03,111 - INFO: Round 27: 6306642/6306642 AI 961578 AW 3502902 Mem 0.945
2019-07-12 15:17:41,899 - INFO: Round 28: 6306642/6306642 AI 961648 AW 3503366 Mem 0.945
2019-07-12 15:18:20,887 - INFO: Round 29: 6306642/6306642 AI 961699 AW 3503928 Mem 0.945
2019-07-12 15:18:59,841 - INFO: Round 30: 6306642/6306642 AI 961776 AW 3504812 Mem 0.945
2019-07-12 15:19:38,785 - INFO: Round 31: 6306642/6306642 AI 961823 AW 3505080 Mem 0.945
2019-07-12 15:20:17,866 - INFO: Round 32: 6306642/6306642 AI 961876 AW 3505714 Mem 0.945
2019-07-12 15:20:56,856 - INFO: Round 33: 6306642/6306642 AI 961924 AW 3506328 Mem 0.945
2019-07-12 15:21:35,929 - INFO: Round 34: 6306642/6306642 AI 961974 AW 3506702 Mem 0.945
2019-07-12 15:22:15,072 - INFO: Round 35: 6306642/6306642 AI 961996 AW 3506968 Mem 0.945
2019-07-12 15:22:54,365 - INFO: Round 36: 6306642/6306642 AI 962045 AW 3507534 Mem 0.945
2019-07-12 15:23:33,643 - INFO: Round 37: 6306642/6306642 AI 962170 AW 3508680 Mem 0.946
2019-07-12 15:24:12,745 - INFO: Round 38: 6306642/6306642 AI 962249 AW 3509478 Mem 0.946
2019-07-12 15:24:50,125 - INFO: Round 39: 6306642/6306642 AI 962296 AW 3509930 Mem 0.946
2019-07-12 15:25:27,673 - INFO: Round 40: 6306642/6306642 AI 962349 AW 3510238 Mem 0.946
2019-07-12 15:26:05,631 - INFO: Round 41: 6306642/6306642 AI 962352 AW 3510256 Mem 0.946
2019-07-12 15:26:44,565 - INFO: Round 42: 6306642/6306642 AI 962352 AW 3510256 Mem 0.946
2019-07-12 15:26:44,565 - INFO: No more reads found and terminated ...
2019-07-12 15:27:03,253 - INFO: Extending finished.

2019-07-12 15:27:03,643 - INFO: Separating filtered fastq file ... 
2019-07-12 15:27:11,428 - INFO: Setting '-k 21,45,65,85,105'
2019-07-12 15:27:11,428 - INFO: Assembling using SPAdes ...
2019-07-12 15:37:22,731 - INFO: Insert size = 254.621, deviation = 59.3392, left quantile = 186, right quantile = 332
2019-07-12 15:37:22,732 - INFO: Assembling finished.

2019-07-12 15:37:22,732 - INFO: Slimming assembly graphs ...
2019-07-12 15:37:31,381 - INFO: Slimming _mitochondrion/filtered_spades/K105/assembly_graph.fastg finished!
2019-07-12 15:37:34,088 - INFO: Slimming _mitochondrion/filtered_spades/K85/assembly_graph.fastg finished!
2019-07-12 15:37:36,850 - INFO: Slimming _mitochondrion/filtered_spades/K65/assembly_graph.fastg finished!
2019-07-12 15:37:39,071 - INFO: Slimming _mitochondrion/filtered_spades/K45/assembly_graph.fastg finished!
2019-07-12 15:37:39,072 - INFO: Slimming assembly graphs finished

2019-07-12 15:37:39,084 - INFO: Extracting embplant_mt from the assemblies ...
2019-07-12 15:37:39,087 - INFO: Disentangling _mitochondrion/filtered_spades/K105/assembly_graph.fastg.extend-embplant_mt-embplant_pt.fastg as a circular genome ... 
2019-07-12 15:37:39,151 - ERROR: 
Traceback (most recent call last):
  File "/home/polli104@chapman.edu/Hagop/./GetOrganelle/get_organelle_from_reads.py", line 3346, in extract_organelle_genome
    temp_graph=graph_temp_file)
  File "/home/polli104@chapman.edu/Hagop/./GetOrganelle/get_organelle_from_reads.py", line 3307, in disentangle_assembly
    acyclic_allowed_in=here_acyclic_allowed, verbose_in=here_verbose, in_temp_graph=temp_graph)
  File "/home/polli104@chapman.edu/Hagop/GetOrganelle/GetOrganelleLib/pipe_control_func.py", line 85, in func_modified
    r = func(*args, **kwargs)
  File "/home/polli104@chapman.edu/Hagop/./GetOrganelle/get_organelle_from_reads.py", line 3193, in disentangle_inside
    temp_graph=in_temp_graph)
  File "/home/polli104@chapman.edu/Hagop/GetOrganelle/GetOrganelleLib/assembly_parser.py", line 1941, in find_target_graph
    str(new_assembly.vertex_info[del_v].other_attr["tags"][database_name]))
KeyError: 'tags'
2019-07-12 15:37:39,171 - ERROR: 
Traceback (most recent call last):
  File "/home/polli104@chapman.edu/Hagop/./GetOrganelle/get_organelle_from_reads.py", line 3346, in extract_organelle_genome
    temp_graph=graph_temp_file)
  File "/home/polli104@chapman.edu/Hagop/./GetOrganelle/get_organelle_from_reads.py", line 3307, in disentangle_assembly
    acyclic_allowed_in=here_acyclic_allowed, verbose_in=here_verbose, in_temp_graph=temp_graph)
  File "/home/polli104@chapman.edu/Hagop/GetOrganelle/GetOrganelleLib/pipe_control_func.py", line 85, in func_modified
    r = func(*args, **kwargs)
  File "/home/polli104@chapman.edu/Hagop/./GetOrganelle/get_organelle_from_reads.py", line 3193, in disentangle_inside
    temp_graph=in_temp_graph)
  File "/home/polli104@chapman.edu/Hagop/GetOrganelle/GetOrganelleLib/assembly_parser.py", line 1941, in find_target_graph
    str(new_assembly.vertex_info[del_v].other_attr["tags"][database_name]))
KeyError: 'tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/polli104@chapman.edu/Hagop/./GetOrganelle/get_organelle_from_reads.py", line 3815, in main
    options=options)
  File "/home/polli104@chapman.edu/Hagop/./GetOrganelle/get_organelle_from_reads.py", line 3359, in extract_organelle_genome
    sys.exit()
SystemExit

Total cost 2617.58 s
Please email jinjianjun@mail.kib.ac.cn or phylojin@163.com if you find bugs!
Please provide me with the get_org.log.txt file!
```

**Comment by Kinggerm** [comment]
Can you attach the complete log file please? I need to see the version information.

**Comment by pollend** [comment]
```
GetOrganelle v1.6.2a

get_organelle_from_reads.py assembles organelle genomes from genome skimming data.
Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.

Python 3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 02:32:25)  [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
Python libs: numpy 1.14.3; sympy 1.3; scipy 1.2.0; psutil 5.4.8
Dependencies: Bowtie2 2.3.5.1; SPAdes 3.13.0; Blast 2.2.30
```

**Comment by Kinggerm** [comment]
Thanks for adding this. I am doing field work these days and sorry for the intermittent replay.
This is a minor bug. This happened when it failed in disentangling. Usually it should just report failed without error. I just fixed it in 1.6.2b. Please update to the latest version.
BTW, plant mitogenome is usually full of repeats and hard to disentangle. Besides you are using limited dataset for mitogenome. I am afraid of your chance to get the complete mitogenome is limited.

Thanks for reporting this.

Jianjun

**Comment by sivajean** [comment]
hi sir,
same problem here,


GetOrganelle v1.6.2e

get_organelle_from_reads.py assembles organelle genomes from genome skimming data.
Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.

Python 2.7.12 (default, Nov 12 2018, 14:36:49)  [GCC 5.4.0 20160609]
Python libs: numpy 1.11.0; sympy 1.5.1; scipy 0.17.0; psutil 3.4.2
Dependencies: Bowtie2 2.3.5.1; SPAdes 3.13.0; Blast 2.2.30
get_organelle_from_reads.py -1 TRI-1_1.fastq -2 TRI-1_2.fastq -o mitochondria_output -R 50 -k 21,45,
65,85,105 -P 1000000 -F embplant_mt

2020-01-17 19:09:22,393 - INFO: Pre-reading fastq ...
2020-01-17 19:09:22,393 - INFO: Estimating reads to use ... (to skip, set '--reduce-reads-for-covera
ge inf')
2020-01-17 19:09:23,136 - INFO: Tasting 100000+100000 reads ...
2020-01-17 19:09:35,943 - INFO: Tasting 500000+500000 reads ...
2020-01-17 19:10:08,596 - INFO: Tasting 2500000+2500000 reads ...
2020-01-17 19:12:44,394 - INFO: Tasting 12500000+12500000 reads ...

GetOrganelle v1.6.2e

get_organelle_from_reads.py assembles organelle genomes from genome skimming data.
Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.

Python 2.7.12 (default, Nov 12 2018, 14:36:49)  [GCC 5.4.0 20160609]
Python libs: numpy 1.11.0; sympy 1.5.1; scipy 0.17.0; psutil 3.4.2
Dependencies: Bowtie2 2.3.5.1; SPAdes 3.13.0; Blast 2.2.30
get_organelle_from_reads.py -1 TRI-1_1.fastq -2 TRI-1_2.fastq -o mitochondria_output -R 50 -k 21,45,
65,85,105 -P 1000000 -F embplant_mt -t 20

2020-01-17 19:16:13,727 - INFO: Pre-reading fastq ...
2020-01-17 19:16:13,727 - INFO: Estimating reads to use ... (to skip, set '--reduce-reads-for-covera
ge inf')
2020-01-17 19:16:14,445 - INFO: Tasting 100000+100000 reads ...
2020-01-17 19:16:24,746 - INFO: Tasting 500000+500000 reads ...
2020-01-17 19:16:48,361 - INFO: Tasting 2500000+2500000 reads ...
2020-01-17 19:18:42,279 - INFO: Tasting 12500000+12500000 reads ...
2020-01-17 19:28:01,239 - INFO: Estimating reads to use finished.
2020-01-17 19:29:32,428 - INFO: Counting read qualities ...
2020-01-17 19:29:32,639 - INFO: Identified quality encoding format = Illumina 1.8+
2020-01-17 19:29:32,642 - INFO: Trimming bases with qualities (0.00%): 33..33  !
2020-01-17 19:29:32,751 - INFO: Mean error rate = 0.0056
2020-01-17 19:29:32,751 - INFO: Counting read lengths ...
2020-01-17 19:31:21,061 - INFO: Mean = 150.0 bp, maximum = 151 bp.
2020-01-17 19:31:21,061 - INFO: Reads used = 34911164+34911164
2020-01-17 19:31:21,061 - INFO: Pre-reading fastq finished.

2020-01-17 19:31:21,061 - INFO: Making seed reads ...
2020-01-17 19:31:21,062 - INFO: Seed bowtie2 index existed!
2020-01-17 19:31:21,062 - INFO: Mapping reads to seed bowtie2 index ...
2020-01-17 19:51:44,440 - INFO: Mapping finished.
2020-01-17 19:51:44,441 - INFO: Seed reads made: mitochondria_output/seed/embplant_mt.initial.fq (86
36086 bytes)
2020-01-17 19:51:44,441 - INFO: Making seed reads finished.

2020-01-17 19:51:44,441 - INFO: Checking seed reads and parameters ...
2020-01-17 19:51:44,441 - INFO: The automatically-estimated parameter(s) do not ensure the best choi
ce(s).
2020-01-17 19:51:44,442 - INFO: If the result graph is not a circular organelle genome,
2020-01-17 19:51:44,442 - INFO:   you could adjust the value(s) of '-w'/'-R' for another new run.
2020-01-17 19:51:47,269 - INFO: Pre-assembling mapped reads ...
2020-01-17 19:51:52,220 - INFO: Pre-assembling mapped reads finished.
2020-01-17 19:51:52,220 - INFO: Estimated embplant_mt-hitting base-coverage = 49.54
2020-01-17 19:51:52,221 - INFO: Estimated word size(s): 85
2020-01-17 19:51:52,221 - INFO: Setting '-w 85'
2020-01-17 19:51:52,221 - INFO: Setting '--max-extending-len inf'
2020-01-17 19:51:52,334 - INFO: Checking seed reads and parameters finished.

2020-01-17 19:51:52,335 - INFO: Making read index ...
2020-01-17 20:12:04,505 - INFO: Mem 11.147 G, 66731260 candidates in all 69822328 reads
2020-01-17 20:12:04,826 - INFO: Pre-grouping reads ...
2020-01-17 20:12:04,826 - INFO: Setting '--pre-w 85'
2020-01-17 20:12:15,712 - INFO: Mem 11.871 G, 1000000/2599095 used/duplicated
2020-01-17 20:17:03,825 - INFO: Mem 29.056 G, 42771 groups made.
2020-01-17 20:17:19,278 - INFO: Making read index finished.

2020-01-17 20:17:21,087 - INFO: Extending ...
2020-01-17 20:17:21,092 - INFO: Adding initial words ...
2020-01-17 20:17:22,831 - INFO: AW 852868
2020-01-17 20:31:27,704 - INFO: Round 1: 66731260/66731260 AI 2111771 AW 50639688 Mem 18.295
2020-01-17 20:52:29,253 - INFO: Round 2: 66731260/66731260 AI 11848345 AW 237069260 Mem 48.236
2020-01-17 21:08:59,068 - INFO: Round 3: 66731260/66731260 AI 15071024 AW 305249294 Mem 56.626
2020-01-17 21:23:59,802 - INFO: Round 4: 66731260/66731260 AI 16312433 AW 337211070 Mem 60.559
2020-01-17 21:39:52,662 - INFO: Round 5: 66731260/66731260 AI 17091449 AW 359373318 Mem 71.286
2020-01-17 21:54:13,421 - INFO: Round 6: 66731260/66731260 AI 17700890 AW 377333402 Mem 73.496
2020-01-17 22:08:38,370 - INFO: Round 7: 66731260/66731260 AI 18206429 AW 392512646 Mem 75.364
2020-01-17 22:23:03,493 - INFO: Round 8: 66731260/66731260 AI 18647628 AW 405543156 Mem 76.968
2020-01-17 22:37:29,216 - INFO: Round 9: 66731260/66731260 AI 19005017 AW 416308600 Mem 78.292
2020-01-17 22:51:54,407 - INFO: Round 10: 66731260/66731260 AI 19317951 AW 425656550 Mem 79.443
2020-01-17 23:06:21,378 - INFO: Round 11: 66731260/66731260 AI 19578733 AW 433396962 Mem 80.395
2020-01-17 23:20:47,656 - INFO: Round 12: 66731260/66731260 AI 19794676 AW 439862562 Mem 81.191
2020-01-17 23:35:14,325 - INFO: Round 13: 66731260/66731260 AI 19977022 AW 445369768 Mem 81.868
2020-01-17 23:49:42,285 - INFO: Round 14: 66731260/66731260 AI 20134016 AW 450133328 Mem 82.455
2020-01-18 00:04:12,082 - INFO: Round 15: 66731260/66731260 AI 20278283 AW 454351896 Mem 82.974
2020-01-18 00:18:39,727 - INFO: Round 16: 66731260/66731260 AI 20397571 AW 457920316 Mem 83.413
2020-01-18 00:33:11,316 - INFO: Round 17: 66731260/66731260 AI 20500786 AW 461007838 Mem 83.793
2020-01-18 00:47:44,921 - INFO: Round 18: 66731260/66731260 AI 20591497 AW 463730994 Mem 84.128
2020-01-18 01:02:16,086 - INFO: Round 19: 66731260/66731260 AI 20670959 AW 466101628 Mem 84.42
2020-01-18 01:16:45,213 - INFO: Round 20: 66731260/66731260 AI 20739246 AW 468148722 Mem 84.671
2020-01-18 01:31:14,642 - INFO: Round 21: 66731260/66731260 AI 20796855 AW 469872910 Mem 84.884
2020-01-18 01:45:45,935 - INFO: Round 22: 66731260/66731260 AI 20845479 AW 471337726 Mem 85.064
2020-01-18 02:00:18,946 - INFO: Round 23: 66731260/66731260 AI 20887037 AW 472603918 Mem 85.22
2020-01-18 02:14:49,355 - INFO: Round 24: 66731260/66731260 AI 20924539 AW 473716602 Mem 85.357
2020-01-18 02:29:19,394 - INFO: Round 25: 66731260/66731260 AI 20956481 AW 474669186 Mem 85.474
2020-01-18 02:43:47,960 - INFO: Round 26: 66731260/66731260 AI 20983448 AW 475478094 Mem 85.573
2020-01-18 02:58:17,909 - INFO: Round 27: 66731260/66731260 AI 21007228 AW 476195906 Mem 85.662
2020-01-18 03:12:46,319 - INFO: Round 28: 66731260/66731260 AI 21027656 AW 476806976 Mem 85.737
2020-01-18 03:27:15,438 - INFO: Round 29: 66731260/66731260 AI 21044963 AW 477335980 Mem 85.802
2020-01-18 03:41:44,039 - INFO: Round 30: 66731260/66731260 AI 21059804 AW 477785318 Mem 85.857
2020-01-18 03:56:20,079 - INFO: Round 31: 66731260/66731260 AI 21073306 AW 478187074 Mem 85.907
2020-01-18 04:10:52,934 - INFO: Round 32: 66731260/66731260 AI 21084984 AW 478537110 Mem 85.95
2020-01-18 04:25:22,488 - INFO: Round 33: 66731260/66731260 AI 21095274 AW 478842516 Mem 85.987
2020-01-18 04:39:54,564 - INFO: Round 34: 66731260/66731260 AI 21103810 AW 479094300 Mem 86.018
2020-01-18 04:54:28,559 - INFO: Round 35: 66731260/66731260 AI 21111484 AW 479320006 Mem 86.046
2020-01-18 05:09:04,232 - INFO: Round 36: 66731260/66731260 AI 21118203 AW 479518396 Mem 86.071
2020-01-18 05:23:45,891 - INFO: Round 37: 66731260/66731260 AI 21124226 AW 479691684 Mem 86.092
2020-01-18 05:38:40,497 - INFO: Round 38: 66731260/66731260 AI 21129486 AW 479846954 Mem 86.111
2020-01-18 05:53:23,392 - INFO: Round 39: 66731260/66731260 AI 21134542 AW 479997576 Mem 86.13
2020-01-18 06:08:04,157 - INFO: Round 40: 66731260/66731260 AI 21139428 AW 480134720 Mem 86.146
2020-01-18 06:23:02,448 - INFO: Round 41: 66731260/66731260 AI 21143585 AW 480257262 Mem 86.162
2020-01-18 06:37:37,908 - INFO: Round 42: 66731260/66731260 AI 21147249 AW 480363942 Mem 86.175
2020-01-18 06:52:16,039 - INFO: Round 43: 66731260/66731260 AI 21150572 AW 480461710 Mem 86.187
2020-01-18 07:06:52,671 - INFO: Round 44: 66731260/66731260 AI 21153480 AW 480547598 Mem 86.197
2020-01-18 07:21:33,310 - INFO: Round 45: 66731260/66731260 AI 21156331 AW 480630836 Mem 86.207
2020-01-18 07:36:11,084 - INFO: Round 46: 66731260/66731260 AI 21158824 AW 480704762 Mem 86.217
2020-01-18 07:50:53,511 - INFO: Round 47: 66731260/66731260 AI 21161162 AW 480772628 Mem 86.225
2020-01-18 08:05:38,382 - INFO: Round 48: 66731260/66731260 AI 21163145 AW 480828960 Mem 86.232
2020-01-18 08:20:19,731 - INFO: Round 49: 66731260/66731260 AI 21164988 AW 480882744 Mem 86.238
2020-01-18 08:34:55,895 - INFO: Round 50: 66731260/66731260 AI 21166712 AW 480934038 Mem 86.245
2020-01-18 08:34:55,895 - INFO: Hit the round limit 50 and terminated ...
2020-01-18 10:10:14,276 - INFO: Extending finished.

2020-01-18 10:10:16,882 - INFO: Separating filtered fastq file ...
2020-01-18 10:12:49,096 - INFO: Setting '-k 21,45,65,85,105'
2020-01-18 10:12:49,096 - INFO: Assembling using SPAdes ...
2020-01-18 17:42:46,852 - INFO: Insert size = 551.987, deviation = 134.982, left quantile = 392, rig
ht quantile = 724
2020-01-18 17:42:46,853 - INFO: Assembling finished.

2020-01-18 17:42:46,853 - INFO: Slimming assembly graphs ...
2020-01-18 18:32:48,819 - INFO: Slimming mitochondria_output/filtered_spades/K105/assembly_graph.fas
tg finished!
2020-01-18 19:29:59,499 - INFO: Slimming mitochondria_output/filtered_spades/K85/assembly_graph.fast
g finished!
2020-01-18 22:36:19,256 - INFO: Slimming mitochondria_output/filtered_spades/K65/assembly_graph.fast
g finished!
2020-01-19 04:33:15,218 - INFO: Slimming mitochondria_output/filtered_spades/K45/assembly_graph.fast
g finished!
2020-01-19 04:33:15,219 - INFO: Slimming assembly graphs finished

2020-01-19 04:33:15,219 - INFO: Extracting embplant_mt from the assemblies ...
2020-01-19 04:33:15,220 - INFO: Disentangling mitochondria_output/filtered_spades/K105/assembly_grap
h.fastg.extend-embplant_mt-embplant_pt.fastg as a circular genome ...
2020-01-19 04:43:15,220 - INFO: Disentangling timeout. (see '--disentangle-time-limit' for more)
2020-01-19 04:43:15,220 - INFO: Disentangling mitochondria_output/filtered_spades/K85/assembly_graph
.fastg.extend-embplant_mt-embplant_pt.fastg as a circular genome ...
2020-01-19 04:53:24,200 - INFO: Disentangling timeout. (see '--disentangle-time-limit' for more)
2020-01-19 04:53:24,202 - INFO: Disentangling mitochondria_output/filtered_spades/K65/assembly_graph
.fastg.extend-embplant_mt-embplant_pt.fastg as a circular genome ...
2020-01-19 05:03:36,534 - INFO: Disentangling timeout. (see '--disentangle-time-limit' for more)
2020-01-19 05:03:36,535 - INFO: Disentangling mitochondria_output/filtered_spades/K45/assembly_graph
.fastg.extend-embplant_mt-embplant_pt.fastg as a circular genome ...
2020-01-19 05:14:18,106 - INFO: Disentangling timeout. (see '--disentangle-time-limit' for more)
2020-01-19 05:14:18,109 - INFO: Disentangling mitochondria_output/filtered_spades/K105/assembly_grap
h.fastg.extend-embplant_mt-embplant_pt.fastg as contig(s) ...
2020-01-19 06:15:32,389 - INFO: Disentangling timeout. (see '--disentangle-time-limit' for more)
2020-01-19 06:15:32,393 - INFO: Disentangling mitochondria_output/filtered_spades/K85/assembly_graph
.fastg.extend-embplant_mt-embplant_pt.fastg as contig(s) ...
2020-01-19 07:15:42,389 - INFO: Disentangling timeout. (see '--disentangle-time-limit' for more)
2020-01-19 07:15:42,395 - INFO: Disentangling mitochondria_output/filtered_spades/K65/assembly_graph
.fastg.extend-embplant_mt-embplant_pt.fastg as contig(s) ...
2020-01-19 08:15:56,728 - INFO: Disentangling timeout. (see '--disentangle-time-limit' for more)
2020-01-19 08:15:56,730 - INFO: Disentangling mitochondria_output/filtered_spades/K45/assembly_graph
.fastg.extend-embplant_mt-embplant_pt.fastg as contig(s) ...
2020-01-19 09:16:38,141 - INFO: Disentangling timeout. (see '--disentangle-time-limit' for more)
2020-01-19 09:16:38,141 - INFO: Please ...
2020-01-19 09:16:38,141 - INFO: load the graph file 'assembly_graph.fastg.extend-embplant_mt-embplan
t_pt.fastg,assembly_graph.fastg' in K105,K85,K65,K45
2020-01-19 09:16:38,141 - INFO: load the CSV file 'assembly_graph.fastg.extend-embplant_mt-embplant_
pt.csv' in K105,K85,K65,K45
2020-01-19 09:16:38,142 - INFO: visualize and export your result in Bandage.
2020-01-19 09:16:38,142 - INFO: If you have questions for us, please provide us with the get_org.log
.txt file and the graph in the format you like!
2020-01-19 09:17:48,156 - INFO: Extracting embplant_mt from the assemblies failed.


Total cost 136894.67 s
Thank you!
Hope you get provide some idea to clear this error

**Comment by Kinggerm** [comment]
Hi,

Please take a look at the log file and do as what it suggested. This is not the same problem. pollend opened this issue for detecting a bug.

Rather than a bug, your case is a matter of the complexity of the data, meaning that at the last step GetOrganelle can not export the path automatically because of the complicated assembly graph (data character) and the default `--disentangle-time-limit 180`.
You could rerun the last step using `disentangle_organelle_assembly.py` with increased disentangle-time-limit, or do manual completion using Bandage. No matter which option you choose, you should visualize the assembly graph in Bandage first to get an overview of your result (as already suggested in the log file: load the graph file 'assembly_graph.fastg.extend-embplant_mt-embplant_pt.fastg,assembly_graph.fastg' and the CSV file 'assembly_graph.fastg.extend-embplant_mt-embplant_pt.csv'). If you have trouble in interpreting the assembly graph in Bandage, please turn on the `depth`/`length`/`CSV data` and post the image here.

Besides, as the mapping suggested, the mitogenome base coverage might be relatively low (49.54), which is not a good sign. But, anyway, please do visualization first to see how it really goes.
