### ISSUE TITLE
(ERR): bowtie2-align exited with value 134

### ISSUE THREAD

**Issue by tulu4411** [Kinggerm/GetOrganelle#184]
Good day,

I am currently having problems running GetOrganelle. When assembling I get the following error:

Error: Read SRR5406130.91536 HWI-ST1348:334:H9MT7ADXX:2:1102:2296:82623/1 has more read characters than quality values.
terminate called after throwing an instance of 'int'
Aborted
(ERR): bowtie2-align exited with value 134

2022-08-03 18:00:52,351 - ERROR: 
Traceback (most recent call last):
  File "/home/tulu4411/anaconda3/envs/bio/bin/get_organelle_from_reads.py", line 3941, in main
    seed_fq, seed_sam, new_seed_f = making_seed_reads_using_mapping(
  File "/home/tulu4411/anaconda3/envs/bio/bin/get_organelle_from_reads.py", line 3040, in making_seed_reads_using_mapping
    map_with_bowtie2(seed_file=seed_file, original_fq_files=original_fq_files,
  File "/home/tulu4411/anaconda3/envs/bio/lib/python3.9/site-packages/GetOrganelleLib/pipe_control_func.py", line 413, in map_with_bowtie2
    raise Exception("")
Exception

Please, I hope you can help me as soon as possible.

I attach the getorganelle log file
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/9285758/get_org.log.txt)

Thanks in advance.

**Comment by Kinggerm** [comment]
https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#err-bowtie2-align-diedexited
