### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by bioramg** [Kinggerm/GetOrganelle#207]
Hello Sir,
I am assembling the plant mitochondrial genome. But I am getting a "MemoryError" while running getorganalle using bioconda. It does not generate any log files or folders in the server. 
Comments:
/home/anaconda3/envs/getorganelle/bin/get_organelle_from_reads.py -1 /home/data/x_1.fastq.gz -2 /home/data/x_2.fastq.gz -o han -R 50 -F embplant_mt -t 40

GETORG_PATH=/home/.GetOrganelle
SEED  DB: embplant_mt 0.0.1; embplant_pt 0.0.1
LABEL DB: embplant_mt 0.0.1; embplant_pt 0.0.1
WORKING DIR: /data/x
/home/anaconda3/envs/getorganelle/bin/get_organelle_from_reads.py -1 /home/data/x_1.fastq.gz -2 /home/data/x_2.fastq.gz -o han -R 50 -F embplant_mt -t 40

2022-10-26 18:36:38,329 - INFO: Pre-reading fastq ...
2022-10-26 18:36:38,329 - INFO: Estimating reads to use ... (to use all reads, set '--reduce-reads-for-coverage inf --max-reads inf')
2022-10-26 18:36:38,436 - INFO: Tasting 100000+100000 reads ...
Error with running SPAdes: == Error ==  system call for: "['/home/anaconda3/envs/getorganelle/share/spades-3.13.0-0/bin/spades-core', '/data/x/x/check/1/embplant_mt.check.fq.spades/K45/configs/config.info']" finished abnormally, err code: -6
2022-10-26 18:36:50,794 - INFO: Tasting 500000+500000 reads ...
2022-10-26 18:37:07,876 - INFO: Tasting 2500000+2500000 reads ...
2022-10-26 18:38:17,483 - INFO: Estimating reads to use finished.
2022-10-26 18:38:17,483 - INFO: Unzipping reads file: /home/data/x_1.fastq.gz (3994639172 bytes)
2022-10-26 18:40:15,550 - INFO: Unzipping reads file: /home/data/x_2.fastq.gz (5004022231 bytes)
2022-10-26 18:42:26,974 - INFO: Counting read qualities ...
2022-10-26 18:42:27,156 - INFO: Identified quality encoding format = Illumina 1.8+
2022-10-26 18:42:27,156 - INFO: Phred offset = 33
2022-10-26 18:42:27,158 - INFO: Trimming bases with qualities (0.00%): 33..33  !
2022-10-26 18:42:27,221 - INFO: Mean error rate = 0.0055
2022-10-26 18:42:27,222 - INFO: Counting read lengths ...
2022-10-26 18:44:34,848 - INFO: Mean = 151.0 bp, maximum = 151 bp.
2022-10-26 18:44:34,848 - INFO: Reads used = 50886746+50886746
2022-10-26 18:44:34,848 - INFO: Pre-reading fastq finished.

2022-10-26 18:44:34,848 - INFO: Making seed reads ...
2022-10-26 18:44:34,848 - INFO: Seed bowtie2 index existed!
2022-10-26 18:44:34,849 - INFO: Mapping reads to seed bowtie2 index ...
2022-10-26 19:01:24,034 - INFO: Mapping finished.
2022-10-26 19:01:24,035 - INFO: Seed reads made: x/seed/embplant_mt.initial.fq (32341487 bytes)
2022-10-26 19:01:24,036 - INFO: Making seed reads finished.

2022-10-26 19:01:24,036 - INFO: Checking seed reads and parameters ...
2022-10-26 19:01:24,036 - INFO: The automatically-estimated parameter(s) do not ensure the best choice(s).
2022-10-26 19:01:24,036 - INFO: If the result graph is not a circular organelle genome,
2022-10-26 19:01:24,037 - INFO:   you could adjust the value(s) of '-w'/'-R' for another new run.
2022-10-26 19:01:28,094 - INFO: Pre-assembling mapped reads ...
2022-10-26 19:01:36,532 - INFO: Pre-assembling mapped reads finished.
2022-10-26 19:01:36,533 - INFO: Estimated embplant_mt-hitting base-coverage = 132.12
2022-10-26 19:01:36,701 - INFO: Estimated word size(s): 86
2022-10-26 19:01:36,702 - INFO: Setting '-w 86'
2022-10-26 19:01:36,702 - INFO: Setting '--max-extending-len inf'
2022-10-26 19:01:36,842 - INFO: Checking seed reads and parameters finished.

2022-10-26 19:01:36,843 - INFO: Making read index ...
2022-10-26 19:15:07,311 - INFO: 97621454 candidates in all 101773492 reads
2022-10-26 19:15:07,583 - INFO: Pre-grouping reads ...
2022-10-26 19:15:07,583 - INFO: Setting '--pre-w 86'
2022-10-26 19:15:17,152 - INFO: 200000/3388497 used/duplicated
2022-10-26 19:16:04,370 - INFO: 3740 groups made.
2022-10-26 19:16:20,231 - INFO: Making read index finished.

2022-10-26 19:16:20,232 - INFO: Extending ...
2022-10-26 19:16:20,232 - INFO: Adding initial words ...
2022-10-26 19:16:24,128 - INFO: AW 2239440
2022-10-26 19:31:56,652 - INFO: Round 1: 97621454/97621454 AI 4667236 AW 111362180
2022-10-26 19:52:03,285 - INFO: Round 2: 97621454/97621454 AI 16482978 AW 355700617
2022-10-26 20:08:42,490 - INFO: Round 3: 97621454/97621454 AI 22435771 AW 515322177
2022-10-26 20:23:46,775 - INFO: Round 4: 97621454/97621454 AI 26286937 AW 625400103
2022-10-26 20:37:52,195 - INFO: Round 5: 97621454/97621454 AI 29030186 AW 705546699
2022-10-26 20:51:16,446 - INFO: Round 6: 97621454/97621454 AI 31085309 AW 766100073
2022-10-26 21:03:42,266 - INFO: Round 7: 97621454/97621454 AI 32669040 AW 812904125
2022-10-26 21:15:48,350 - INFO: Round 8: 97621454/97621454 AI 33919001 AW 849813678
2022-10-26 21:27:43,994 - INFO: Round 9: 97621454/97621454 AI 34915502 AW 879220032
2022-10-26 21:39:26,313 - INFO: Round 10: 97621454/97621454 AI 35722533 AW 903032156
2022-10-26 21:51:00,488 - INFO: Round 11: 97621454/97621454 AI 36381694 AW 922430604
2022-10-26 22:02:28,993 - INFO: Round 12: 97621454/97621454 AI 36931018 AW 938556034
2022-10-26 22:13:45,945 - INFO: Round 13: 97621454/97621454 AI 37386272 AW 951909104
2022-10-26 22:24:34,630 - INFO: Round 14: 97621454/97621454 AI 37766200 AW 963041264
2022-10-26 22:35:19,529 - INFO: Round 15: 97621454/97621454 AI 38082664 AW 972336170
2022-10-26 22:46:02,106 - INFO: Round 16: 97621454/97621454 AI 38353314 AW 980250908
2022-10-26 22:56:39,951 - INFO: Round 17: 97621454/97621454 AI 38577706 AW 986795742
2022-10-26 23:07:15,544 - INFO: Round 18: 97621454/97621454 AI 38765093 AW 992257206
2022-10-26 23:17:49,440 - INFO: Round 19: 97621454/97621454 AI 38922458 AW 996853522
2022-10-26 23:28:20,814 - INFO: Round 20: 97621454/97621454 AI 39056098 AW 1000759166
2022-10-26 23:38:51,299 - INFO: Round 21: 97621454/97621454 AI 39168690 AW 1004049212
2022-10-26 23:49:20,765 - INFO: Round 22: 97621454/97621454 AI 39264507 AW 1006861156
2022-10-26 23:59:49,103 - INFO: Round 23: 97621454/97621454 AI 39346584 AW 1009250492
2022-10-27 00:10:17,449 - INFO: Round 24: 97621454/97621454 AI 39415261 AW 1011259188
2022-10-27 00:20:44,403 - INFO: Round 25: 97621454/97621454 AI 39474548 AW 1012989690
2022-10-27 00:31:09,308 - INFO: Round 26: 97621454/97621454 AI 39524536 AW 1014446338
2022-10-27 00:41:34,282 - INFO: Round 27: 97621454/97621454 AI 39566999 AW 1015675074
2022-10-27 00:52:00,748 - INFO: Round 28: 97621454/97621454 AI 39603428 AW 1016737602
2022-10-27 01:02:24,389 - INFO: Round 29: 97621454/97621454 AI 39634115 AW 1017623714
2022-10-27 01:12:47,660 - INFO: Round 30: 97621454/97621454 AI 39660560 AW 1018395188
2022-10-27 01:23:10,488 - INFO: Round 31: 97621454/97621454 AI 39683598 AW 1019056000
2022-10-27 01:33:34,130 - INFO: Round 32: 97621454/97621454 AI 39703482 AW 1019630120
2022-10-27 01:44:01,523 - INFO: Round 33: 97621454/97621454 AI 39720766 AW 1020131552
2022-10-27 01:54:24,800 - INFO: Round 34: 97621454/97621454 AI 39735859 AW 1020567116
2022-10-27 02:04:47,554 - INFO: Round 35: 97621454/97621454 AI 39748962 AW 1020949556
2022-10-27 02:15:10,588 - INFO: Round 36: 97621454/97621454 AI 39760551 AW 1021284672
2022-10-27 02:25:31,565 - INFO: Round 37: 97621454/97621454 AI 39770139 AW 1021558354
2022-10-27 02:36:01,526 - INFO: Round 38: 97621454/97621454 AI 39778124 AW 1021790328
2022-10-27 02:46:23,278 - INFO: Round 39: 97621454/97621454 AI 39785172 AW 1021993602
2022-10-27 02:56:44,274 - INFO: Round 40: 97621454/97621454 AI 39791459 AW 1022170944
2022-10-27 03:07:05,393 - INFO: Round 41: 97621454/97621454 AI 39796838 AW 1022326336
2022-10-27 03:17:30,994 - INFO: Round 42: 97621454/97621454 AI 39801364 AW 1022452210
2022-10-27 03:28:00,529 - INFO: Round 43: 97621454/97621454 AI 39805126 AW 1022562760
2022-10-27 03:38:21,141 - INFO: Round 44: 97621454/97621454 AI 39808772 AW 1022669348
2022-10-27 03:48:46,306 - INFO: Round 45: 97621454/97621454 AI 39811997 AW 1022763730
2022-10-27 03:59:06,348 - INFO: Round 46: 97621454/97621454 AI 39814621 AW 1022836994
2022-10-27 04:09:26,933 - INFO: Round 47: 97621454/97621454 AI 39816792 AW 1022897850
2022-10-27 04:19:49,116 - INFO: Round 48: 97621454/97621454 AI 39818662 AW 1022951064
2022-10-27 04:30:09,080 - INFO: Round 49: 97621454/97621454 AI 39820191 AW 1022994522
2022-10-27 04:40:29,002 - INFO: Round 50: 97621454/97621454 AI 39821493 AW 1023032820
2022-10-27 04:40:29,002 - INFO: Hit the round limit 50 and terminated ...
2022-10-27 16:08:33,521 - INFO: Extending finished.

2022-10-27 16:08:35,550 - INFO: Separating extended fastq file ...
2022-10-27 16:08:37,878 - ERROR:
Traceback (most recent call last):
  File "/home/anaconda3/envs/getorganelle/bin/get_organelle_from_reads.py", line 4064, in main
    reads_paired['pair_out'] = separate_fq_by_pair(out_base, options.prefix, verb_log, log_handler)
  File "/home/anaconda3/envs/getorganelle/bin/get_organelle_from_reads.py", line 3327, in separate_fq_by_pair
    output_u_2=out_unpaired_2)
  File "/home/anaconda3/envs/getorganelle/lib/python3.6/site-packages/GetOrganelleLib/seq_parser.py", line 1649, in get_paired_and_unpaired_reads
    file_h_1_lines = open(input_fq_1, 'r').readlines()
  File "/home/anaconda3/envs/getorganelle/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
MemoryError

Total cost 77527.09 s
Please email jianjun.jin@columbia.edu and jinjianjun@mail.kib.ac.cn if you find bugs!
Please provide me with the get_org.log.txt file!

How to fix this issue. 
Thank you.

**Comment by Kinggerm** [comment]
Please see here: https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#memoryerror

Besides, I would increase the word size (e.g. -w 95) and/or reduce the rounds (e.g. -R 15).
