### ISSUE TITLE
(ERR): bowtie2-align exited with value 137

### ISSUE THREAD

**Issue by jwang147** [Kinggerm/GetOrganelle#225]
I ran GetOrganelle to assemble a chloroplast genome. However, the program failed and got the following error message:

cat sy_output/get_org.log.txt

GetOrganelle v1.7.5

get_organelle_from_reads.py assembles organelle genomes from genome skimming data.
Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.

Python 3.9.5 (default, Jun  4 2021, 12:28:51)  [GCC 7.5.0]
PLATFORM: Linux xulab-1 5.11.0-46-generic #51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022 x86_64 x86_64
PYTHON LIBS: GetOrganelleLib 1.7.5; numpy 1.20.3; sympy 1.8; scipy 1.6.2
DEPENDENCIES: Bowtie2 2.4.4; SPAdes 3.13.0; Blast 2.5.0
GETORG_PATH=/home/jwang/.GetOrganelle
SEED  DB: embplant_pt 0.0.1; embplant_mt 0.0.1
LABEL DB: embplant_pt 0.0.1; embplant_mt 0.0.1
WORKING DIR: /data/jwang/0-2022-cp_genome/0-qjt/1-get-out
/home/jwang/miniconda3/envs/getorganelle/bin/get_organelle_from_reads.py -u sy-cp_12.fq -t 35 -o sy_output -R 30 -k 105,121 -P 1000000 -F embplant_pt

2023-01-04 17:47:48,222 - INFO: Pre-reading fastq ...
2023-01-04 17:47:48,222 - INFO: Estimating reads to use ... (to use all reads, set '--reduce-reads-for-coverage inf --max-reads inf')
2023-01-04 17:47:48,302 - INFO: Estimating reads to use finished.
2023-01-04 17:47:50,535 - INFO: Counting read qualities ...
2023-01-04 17:48:13,521 - INFO: Identified quality encoding format = Solexa
2023-01-04 17:48:13,521 - INFO: Phred offset = 64
2023-01-04 17:48:13,521 - WARNING: Max quality score '{'(123:59) in your fastq file exceeds the usual range (59, 104)
2023-01-04 17:48:13,521 - WARNING: Min quality score '"'(34:-30) in your fastq file is under the usual lower boundary (59, 104)
2023-01-04 17:48:14,282 - INFO: Resetting '--min-quality-score -28'
2023-01-04 17:48:14,282 - INFO: Trimming bases with qualities (0.86%): 34..35  "#
2023-01-04 17:48:37,905 - INFO: Mean error rate = 0.7686
2023-01-04 17:48:37,937 - INFO: Counting read lengths ...
2023-01-04 17:48:38,694 - INFO: Mean = 42386.0 bp, maximum = 237556 bp.
2023-01-04 17:48:38,695 - INFO: Reads used = 16020
2023-01-04 17:48:38,695 - INFO: Pre-reading fastq finished.

2023-01-04 17:48:38,695 - INFO: Making seed reads ...
2023-01-04 17:48:38,695 - INFO: Seed bowtie2 index existed!
2023-01-04 17:48:38,695 - INFO: Mapping reads to seed bowtie2 index ...
2023-01-04 17:52:00,386 - ERROR:
Time loading reference: 00:00:00
Time loading forward index: 00:00:00
Time loading mirror index: 00:00:00
Killed
(ERR): bowtie2-align exited with value 137

2023-01-04 17:52:00,388 - ERROR:
Traceback (most recent call last):
  File "/home/jwang/miniconda3/envs/getorganelle/bin/get_organelle_from_reads.py", line 3935, in main
    seed_fq, seed_sam, new_seed_f = making_seed_reads_using_mapping(
  File "/home/jwang/miniconda3/envs/getorganelle/bin/get_organelle_from_reads.py", line 3037, in making_seed_reads_using_mapping
    map_with_bowtie2(seed_file=seed_file, original_fq_files=original_fq_files,
  File "/home/jwang/miniconda3/envs/getorganelle/lib/python3.9/site-packages/GetOrganelleLib/pipe_control_func.py", line 398, in map_with_bowtie2
    raise Exception("")
Exception

Total cost 253.34 s

Or

/home/jwang/miniconda3/bin/get_organelle_from_reads.py -u sy.fq -t 35 -o sy_output -R 30 -k 21,45,65,85,105 -P 1000000 -F embplant_pt

2023-01-04 17:28:52,160 - INFO: Pre-reading fastq ...
2023-01-04 17:28:52,161 - INFO: Estimating reads to use ... (to use all reads, set '--reduce-reads-for-coverage inf --max-reads inf')
2023-01-04 17:28:52,246 - INFO: Tasting 100000 reads ...

Error: Killed
(ERR): bowtie2-align exited with value 137

2023-01-04 17:32:16,799 - ERROR:
Traceback (most recent call last):
  File "/home/jwang/miniconda3/bin/get_organelle_from_reads.py", line 3870, in main
    all_read_nums = estimate_maximum_n_reads_using_mapping(
  File "/home/jwang/miniconda3/bin/get_organelle_from_reads.py", line 1106, in estimate_maximum_n_reads_using_mapping
    map_with_bowtie2(
  File "/home/jwang/miniconda3/lib/python3.9/site-packages/GetOrganelleLib/pipe_control_func.py", line 398, in map_with_bowtie2
    raise Exception("")
Exception

Total cost 205.84 s

Please help me to fix this issue.

Thank you!

**Comment by Kinggerm** [comment]
Currently, GetOrganelle only accepts short-read sequencing reads.
According to the read lengths and qualities, the input data does not seem qualified.
