### ISSUE TITLE
AttributeError: 'Process' object has no attribute 'memory_info'

### ISSUE THREAD

**Issue by sihellem** [Kinggerm/GetOrganelle#23]
Hi @Kinggerm,

I installed GetOgranelle with these settings on a new cluster that I am using:
```
GetOrganelle v1.6.2e

get_organelle_from_reads.py assembles organelle genomes from genome skimming data.
Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.

Python 2.7.5 (default, Nov 20 2015, 02:00:19)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
Python libs: numpy 1.7.1; sympy 1.4; scipy 0.12.1; psutil 1.2.1
Dependencies: Bowtie2 2.3.5.1; SPAdes 3.13.0; Blast 2.2.30
/home/s/simon-hellemans/.local/bin/get_organelle_from_reads.py -1 12740_R1.fastq.gz -2 12740_R2.fastq.gz -s Termes_genome_sequence.fasta.txt --genes Termes_gene_features_sequence.txt -o Cavi_GetOrg -R 3 -k 21,45,65,85,105 -F animal_mt
```

I launched a first job but there was an issue during the Making read index step:

```
2019-11-16 11:28:17,483 - INFO: Making read index ...
2019-11-16 11:28:17,486 - INFO: 1 reads2019-11-16 11:28:18,013 - INFO: 54322 reads2019-11-16 11:28:18,541 - INFO: 108643 reads2019-11-16 11:28:19,107 - INFO: 162964 reads2019-11-16 11:28:19,684 - INFO: 217285 reads2019-11-16 11:28:20,311 - INFO: 271606 reads2019-11-16 11:28:20,969 - INFO: 325927 reads2019-11-16 11:28:21,470 - INFO: 380248 reads2019-11-16 11:28:22,188 - INFO: 434569 reads2019-11-16 11:28:22,684 - INFO: 488890 reads2019-11-16 11:28:23,430 - INFO: 543211 reads2019-11-16 11:28:23,917 - INFO: 597532 reads2019-11-16 11:28:24,732 - INFO: 651853 reads2019-11-16 11:28:25,225 - INFO: 706174 reads2019-11-16 11:28:25,735 - INFO: 760495 reads2019-11-16 11:28:26,567 - INFO: 814816 reads2019-11-16 11:28:27,158 - INFO: 869137 reads2019-11-16 11:28:27,646 - INFO: 923458 reads2019-11-16 11:28:28,126 - INFO: 977779 reads2019-11-16 11:28:28,914 - INFO: 1032100 reads2019-11-16 11:28:29,656 - INFO: 1086421 reads2019-11-16 11:28:30,149 - INFO: 1140742 reads2019-11-16 11:28:30,630 - INFO: 1195063 reads2019-11-16 11:28:31,124 - INFO: 1249384 reads2019-11-16 11:28:31,611 - INFO: 1303705 reads2019-11-16 11:28:32,770 - INFO: 1358026 reads2019-11-16 11:28:33,262 - INFO: 1412347 reads2019-11-16 11:28:33,811 - INFO: 1466668 reads2019-11-16 11:28:34,292 - INFO: 1520989 reads2019-11-16 11:28:34,777 - INFO: 1575310 reads2019-11-16 11:28:35,262 - INFO: 1629631 reads2019-11-16 11:28:36,661 - INFO: 1683952 reads2019-11-16 11:28:37,146 - INFO: 1738273 reads2019-11-16 11:28:37,634 - INFO: 1792594 reads2019-11-16 11:28:38,119 - INFO: 1846915 reads2019-11-16 11:28:38,606 - INFO: 1901236 reads2019-11-16 11:28:39,086 - INFO: 1955557 reads2019-11-16 11:28:39,579 - INFO: 2009878 reads2019-11-16 11:28:40,066 - INFO: 2064199 reads2019-11-16 11:28:41,664 - INFO: 2118520 reads2019-11-16 11:28:42,152 - INFO: 2172841 reads2019-11-16 11:28:42,637 - INFO: 2227162 reads2019-11-16 11:28:43,130 - INFO: 2281483 reads2019-11-16 11:28:43,613 - INFO: 2335804 reads2019-11-16 11:28:44,092 - INFO: 2390125 reads2019-11-16 11:28:44,575 - INFO: 2444446 reads2019-11-16 11:28:45,067 - INFO: 2498767 reads2019-11-16 11:28:45,560 - INFO: 2553088 reads2019-11-16 11:28:46,050 - INFO: 2607409 reads2019-11-16 11:28:47,873 - INFO: 2661730 reads2019-11-16 11:28:48,357 - INFO: 2716051 reads2019-11-16 11:28:48,841 - INFO: 2770372 reads2019-11-16 11:28:49,334 - INFO: 2824693 reads2019-11-16 11:28:49,959 - INFO: 2879014 reads2019-11-16 11:28:50,438 - INFO: 2933335 reads2019-11-16 11:28:50,921 - INFO: 2987656 reads2019-11-16 11:28:51,402 - INFO: 3041977 reads2019-11-16 11:28:51,883 - INFO: 3096298 reads2019-11-16 11:28:52,381 - INFO: 3150619 reads2019-11-16 11:28:52,873 - INFO: 3204940 reads2019-11-16 11:28:53,374 - INFO: 3259261 reads2019-11-16 11:28:55,691 - INFO: 3313582 reads2019-11-16 11:28:56,177 - INFO: 3367903 reads2019-11-16 11:28:56,657 - INFO: 3422224 reads2019-11-16 11:28:57,147 - INFO: 3476545 reads2019-11-16 11:28:57,631 - INFO: 3530866 reads2019-11-16 11:28:58,116 - INFO: 3585187 reads2019-11-16 11:28:58,603 - INFO: 3639508 reads2019-11-16 11:28:59,085 - INFO: 3693829 reads2019-11-16 11:28:59,568 - INFO: 3748150 reads2019-11-16 11:29:00,049 - INFO: 3802471 reads2019-11-16 11:29:00,533 - INFO: 3856792 reads2019-11-16 11:29:01,023 - INFO: 3911113 reads2019-11-16 11:29:01,506 - INFO: 3965434 reads2019-11-16 11:29:01,991 - INFO: 4019755 reads2019-11-16 11:29:02,478 - INFO: 4074076 reads2019-11-16 11:29:04,751 - INFO: 4128397 reads2019-11-16 11:29:05,759 - INFO: 4182718 reads2019-11-16 11:29:06,242 - INFO: 4237039 reads2019-11-16 11:29:06,722 - INFO: 4291360 reads2019-11-16 11:29:07,208 - INFO: 4345681 reads2019-11-16 11:29:07,691 - INFO: 4400002 reads2019-11-16 11:29:08,175 - INFO: 4454323 reads2019-11-16 11:29:08,660 - INFO: 4508644 reads2019-11-16 11:29:09,145 - INFO: 4562965 reads2019-11-16 11:29:09,631 - INFO: 4617286 reads2019-11-16 11:29:10,113 - INFO: 4671607 reads2019-11-16 11:29:10,599 - INFO: 4725928 reads2019-11-16 11:29:11,088 - INFO: 4780249 reads2019-11-16 11:29:11,564 - INFO: 4834570 reads2019-11-16 11:29:12,051 - INFO: 4888891 reads2019-11-16 11:29:12,534 - INFO: 4943212 reads2019-11-16 11:29:13,014 - INFO: 4997533 reads2019-11-16 11:29:13,501 - INFO: 5051854 reads2019-11-16 11:29:13,986 - INFO: 5106175 reads2019-11-16 11:29:14,470 - INFO: 5160496 reads2019-11-16 11:29:17,785 - INFO: 5214817 reads2019-11-16 11:29:18,284 - INFO: 5269138 reads2019-11-16 11:29:18,778 - INFO: 5323459 reads2019-11-16 11:29:19,261 - INFO: 5377780 reads2019-11-16 11:29:19,747 - INFO: 5432101 reads2019-11-16 11:29:20,230 - INFO: 5486422 reads2019-11-16 11:29:20,713 - INFO: 5540743 reads2019-11-16 11:29:21,195 - INFO: 5595064 reads2019-11-16 11:29:21,677 - INFO: 5649385 reads2019-11-16 11:29:22,164 - INFO: 5703706 reads2019-11-16 11:29:22,901 - INFO: 5758027 reads2019-11-16 11:29:23,387 - INFO: 5812348 reads2019-11-16 11:29:23,870 - INFO: 5866669 reads2019-11-16 11:29:24,343 - INFO: 5920990 reads2019-11-16 11:29:24,830 - INFO: 5975311 reads2019-11-16 11:29:25,312 - INFO: 6029632 reads2019-11-16 11:29:25,798 - INFO: 6083953 reads2019-11-16 11:29:26,283 - INFO: 6138274 reads2019-11-16 11:29:26,767 - INFO: 6192595 reads2019-11-16 11:29:27,255 - INFO: 6246916 reads2019-11-16 11:29:27,733 - INFO: 6301237 reads2019-11-16 11:29:28,219 - INFO: 6355558 reads2019-11-16 11:29:28,699 - INFO: 6409879 reads2019-11-16 11:29:29,178 - INFO: 6464200 reads2019-11-16 11:29:33,644 - INFO: 6518521 reads2019-11-16 11:29:34,127 - INFO: 6572842 reads2019-11-16 11:29:34,612 - INFO: 6627163 reads2019-11-16 11:29:35,096 - INFO: 6681484 reads2019-11-16 11:29:35,584 - INFO: 6735805 reads2019-11-16 11:29:36,071 - INFO: 6790126 reads2019-11-16 11:29:36,557 - INFO: 6844447 reads2019-11-16 11:29:37,034 - INFO: 6898768 reads2019-11-16 11:29:37,518 - INFO: 6953089 reads2019-11-16 11:29:38,007 - INFO: 7007410 reads2019-11-16 11:29:38,489 - INFO: 7061731 reads2019-11-16 11:29:38,974 - INFO: 7116052 reads2019-11-16 11:29:39,457 - INFO: 7170373 reads2019-11-16 11:29:39,941 - INFO: 7224694 reads2019-11-16 11:29:40,423 - INFO: 7279015 reads2019-11-16 11:29:40,908 - INFO: 7333336 reads2019-11-16 11:29:41,397 - INFO: 7387657 reads2019-11-16 11:29:41,877 - INFO: 7441978 reads2019-11-16 11:29:42,367 - INFO: 7496299 reads2019-11-16 11:29:42,854 - INFO: 7550620 reads2019-11-16 11:29:43,353 - INFO: 7604941 reads2019-11-16 11:29:43,854 - INFO: 7659262 reads2019-11-16 11:29:44,351 - INFO: 7713583 reads2019-11-16 11:29:44,839 - INFO: 7767904 reads2019-11-16 11:29:45,321 - INFO: 7822225 reads2019-11-16 11:29:45,804 - INFO: 7876546 reads2019-11-16 11:29:46,291 - INFO: 7930867 reads2019-11-16 11:29:46,773 - INFO: 7985188 reads2019-11-16 11:29:47,257 - INFO: 8039509 reads2019-11-16 11:29:47,741 - INFO: 8093830 reads2019-11-16 11:29:53,255 - INFO: 8148151 reads2019-11-16 11:29:53,739 - INFO: 8202472 reads2019-11-16 11:29:54,223 - INFO: 8256793 reads2019-11-16 11:29:54,708 - INFO: 8311114 reads2019-11-16 11:29:55,190 - INFO: 8365435 reads2019-11-16 11:29:55,682 - INFO: 8419756 reads2019-11-16 11:29:56,166 - INFO: 8474077 reads2019-11-16 11:29:56,651 - INFO: 8528398 reads2019-11-16 11:29:57,140 - INFO: 8582719 reads2019-11-16 11:29:57,627 - INFO: 8637040 reads2019-11-16 11:29:58,118 - INFO: 8691361 reads2019-11-16 11:29:58,603 - INFO: 8745682 reads2019-11-16 11:29:59,090 - INFO: 8800003 reads2019-11-16 11:29:59,571 - INFO: 8854324 reads2019-11-16 11:30:00,051 - INFO: 8908645 reads2019-11-16 11:30:00,539 - INFO: 8962966 reads2019-11-16 11:30:01,022 - INFO: 9017287 reads2019-11-16 11:30:01,509 - INFO: 9071608 reads2019-11-16 11:30:01,996 - INFO: 9125929 reads2019-11-16 11:30:02,479 - INFO: 9180250 reads2019-11-16 11:30:02,966 - INFO: 9234571 reads2019-11-16 11:30:03,449 - INFO: 9288892 reads2019-11-16 11:30:03,936 - INFO: 9343213 reads2019-11-16 11:30:04,416 - INFO: 9397534 reads2019-11-16 11:30:04,899 - INFO: 9451855 reads2019-11-16 11:30:05,386 - INFO: 9506176 reads2019-11-16 11:30:05,867 - INFO: 9560497 reads2019-11-16 11:30:06,352 - INFO: 9614818 reads2019-11-16 11:30:06,838 - INFO: 9669139 reads2019-11-16 11:30:07,322 - INFO: 9723460 reads2019-11-16 11:30:07,811 - INFO: 9777781 reads2019-11-16 11:30:08,306 - INFO: 9832102 reads2019-11-16 11:30:08,812 - INFO: 9886423 reads2019-11-16 11:30:09,313 - INFO: 9940744 reads2019-11-16 11:30:09,810 - INFO: 9995065 reads2019-11-16 11:30:10,298 - INFO: 10049386 reads2019-11-16 11:30:10,781 - INFO: 10103707 reads2019-11-16 11:30:17,407 - INFO: 10158028 reads2019-11-16 11:30:26,687 - INFO: 10212349 reads2019-11-16 11:30:27,180 - INFO: 10266670 reads2019-11-16 11:30:27,680 - INFO: 10320991 reads2019-11-16 11:30:28,201 - INFO: 10375312 reads2019-11-16 11:30:28,703 - INFO: 10429633 reads2019-11-16 11:30:29,206 - INFO: 10483954 reads2019-11-16 11:30:29,715 - INFO: 10538275 reads2019-11-16 11:30:30,248 - INFO: 10592596 reads2019-11-16 11:30:30,751 - INFO: 10646917 reads2019-11-16 11:30:31,256 - INFO: 10701238 reads2019-11-16 11:30:31,770 - INFO: 10755559 reads2019-11-16 11:30:32,276 - INFO: 10809880 reads2019-11-16 11:30:32,791 - INFO: 10864201 reads2019-11-16 11:30:33,338 - INFO: 10918522 reads2019-11-16 11:30:33,851 - INFO: 10972843 reads2019-11-16 11:30:34,349 - INFO: 11027164 reads2019-11-16 11:30:34,563 - ERROR: 
Traceback (most recent call last):
  File "/home/s/simon-hellemans/.local/lib/python2.7/site-packages/GetOrganelle-1.6.2e-py2.7.egg/EGG-INFO/scripts/get_organelle_from_reads.py", line 3673, in main
    resume=resume, echo_step=echo_step, log_handler=log_handler)
  File "/home/s/simon-hellemans/.local/lib/python2.7/site-packages/GetOrganelle-1.6.2e-py2.7.egg/EGG-INFO/scripts/get_organelle_from_reads.py", line 1875, in make_read_index
    memory_usage = "Mem " + str(round(this_process.memory_info().rss / 1024.0 / 1024 / 1024, 3)) + " G, "
AttributeError: 'Process' object has no attribute 'memory_info'
```

Do you know how to solve this?

Thank you in advance for your reply,
Best,
Simon

**Comment by Kinggerm** [comment]
Hi Simon,

You are currently using an out-dated version of psutil (1.2.1). Please update your psutil version to >3.0. You may use `pip install -U psutil`.

Good luck,
Jianjun

**Comment by sihellem** [comment]
Hello Jianjun,

Thanks a lot. The installation seems successful now.

Best,
Simon
