### ISSUE TITLE
Using the GFA file (p_utg) exported by hifiasm for assembly with the error "Slimming failed."

### ISSUE THREAD

**Issue by sunjinkkk** [Kinggerm/GetOrganelle#246]
An error occurs when assembling *asm.p_utg.gfa using hifiasm output, but it is normal in *asm.p_ctg.gfa. GetOrganelle is installed by conda v1.7.7.0. The command is `get_organelle_from_assembly.py -t 40 -F embplant_mt -g ldsg.asm.hic.p_utg.gfa -o test6_from_assembly_mt`

The log file is as follows
`
GetOrganelle v1.7.7.0

get_organelle_from_assembly.py isolates organelle genomes from assembly graph.
Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.

Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0]
PLATFORM: Linux node2 4.18.0-305.3.1.el8.x86_64 #1 SMP Tue Jun 1 16:14:33 UTC 2021 x86_64 x86_64
PYTHON LIBS: GetOrganelleLib 1.7.7.0; numpy 1.24.2; sympy 1.11.1; scipy 1.10.1
DEPENDENCIES: Blast 2.13.0
GETORG_PATH=/home/stu_sunjin/.GetOrganelle
LABEL DB: embplant_mt 0.0.1; embplant_pt 0.0.1
WORKING DIR: /home/stu_sunjin/data/luodi
/home/stu_sunjin/biosoft/miniconda/envs/getorganelle/bin/get_organelle_from_assembly.py -t 40 -F embplant_mt -g ldsg.asm.hic.p_utg.gfa -o test6_from_assembly_mt

2023-03-17 14:42:00,209 - INFO: Processing assembly graph ...
2023-03-17 14:42:00,995 - INFO: Processing assembly graph finished.

2023-03-17 14:42:00,995 - INFO: Slimming assembly graph ...
2023-03-17 14:50:25,222 - ERROR: Slimming test6_from_assembly_mt/initial_assembly_graph.gfa failed. Please check *slim.log.txt for details. 
2023-03-17 14:50:25,222 - ERROR: 
2023-03-17 14:42:01,927 - INFO: Slimming file 1/1: test6_from_assembly_mt/initial_assembly_graph.gfa
2023-03-17 14:42:14,380 - INFO: Parsing input finished.
2023-03-17 14:42:24,198 - INFO: Preparing fasta file finished.
2023-03-17 14:42:24,199 - INFO: Executing BLAST to /home/stu_sunjin/.GetOrganelle/LabelDatabase/embplant_mt ...
2023-03-17 14:42:24,199 - INFO: Executing BLAST ...
2023-03-17 14:46:16,261 - INFO: Executing BLAST finished.
2023-03-17 14:46:16,261 - INFO: Executing BLAST to /home/stu_sunjin/.GetOrganelle/LabelDatabase/embplant_mt finished.
2023-03-17 14:46:16,279 - INFO: Parsing blast result finished.
2023-03-17 14:46:16,279 - INFO: Executing BLAST to /home/stu_sunjin/.GetOrganelle/LabelDatabase/embplant_pt ...
2023-03-17 14:46:16,279 - INFO: Executing BLAST ...
2023-03-17 14:50:20,257 - INFO: Executing BLAST finished.
2023-03-17 14:50:20,257 - INFO: Executing BLAST to /home/stu_sunjin/.GetOrganelle/LabelDatabase/embplant_pt finished.
2023-03-17 14:50:20,354 - INFO: Parsing blast result finished.
2023-03-17 14:50:20,385 - INFO: No enough coverage information found.
2023-03-17 14:50:20,395 - INFO: Mapping names ...
2023-03-17 14:50:25,005 - ERROR: 
division by zero
2023-03-17 14:50:25,005 - ERROR: Slimming file 1/1: test6_from_assembly_mt/initial_assembly_graph.gfa failed!

2023-03-17 14:50:25,005 - ERROR: 
Traceback (most recent call last):
  File "/home/stu_sunjin/biosoft/miniconda/envs/getorganelle/bin/slim_graph.py", line 1070, in main
    raise e
  File "/home/stu_sunjin/biosoft/miniconda/envs/getorganelle/bin/slim_graph.py", line 1041, in main
    reduce_matrix(in_names=in_names_r, ex_names=ex_names_r, seq_matrix=this_matrix,
  File "/home/stu_sunjin/biosoft/miniconda/envs/getorganelle/bin/slim_graph.py", line 754, in reduce_matrix
    assembly_graph.reduce_to_subgraph(bait_vertices=in_names,
  File "/home/stu_sunjin/biosoft/miniconda/envs/getorganelle/lib/python3.10/site-packages/GetOrganelleLib/assembly_parser.py", line 2002, in reduce_to_subgraph
    max(1, self.vertex_info[next_v].cov / base_cov)
ZeroDivisionError: division by zero

2023-03-17 14:50:25,222 - ERROR: 
Traceback (most recent call last):
  File "/home/stu_sunjin/biosoft/miniconda/envs/getorganelle/bin/get_organelle_from_assembly.py", line 1019, in main
    exit()
  File "/home/stu_sunjin/biosoft/miniconda/envs/getorganelle/lib/python3.10/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

Total cost 506.30 s

##############################
For trouble-shooting, please 
Firstly, check https://github.com/Kinggerm/GetOrganelle/wiki/FAQ
Secondly, check if there are open/closed issues related at https://github.com/Kinggerm/GetOrganelle/issues
If your problem was still not solved, 
  please open an issue at https://github.com/Kinggerm/GetOrganelle/issues
  please provide the get_org.log.txt and the the slimmed_assembly_graph.* file(s) (can be visualized as *.png to protect your data privacy) if possible!
`

**Comment by chongjing** [comment]
Hi @sunjinkkk , any update or solutions? I got exactly same issue using hifiasm output to extract a plant mitochonrial genome.

**Comment by louisvant** [comment]
I  got an exactly same problem when i use the assembled GTF file from Flye as the input of Getorganelle,  how to solve this problem? use a lower coverage parameter?

**Comment by JianjunJin** [comment]
> I got an exactly same problem when i use the assembled GTF file from Flye as the input of Getorganelle, how to solve this problem? use a lower coverage parameter?

GetOrganelle only support GFA and FASTG format.
Could you attach at least a log file?

**Comment by JianjunJin** [comment]
> Hi @sunjinkkk , any update or solutions? I got exactly same issue using hifiasm output to extract a plant mitochonrial genome.

Log file?

**Comment by louisvant** [comment]
> > Hi @sunjinkkk , any update or solutions? I got exactly same issue using hifiasm output to extract a plant mitochonrial genome.
> 
> Log file?
Hi, Dr. Jin. here is the log file of getorganelle and slim, please help to check it. thank you!
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/14154653/get_org.log.txt)
[slimmed_assembly_graph.slim.log.txt](https://github.com/Kinggerm/GetOrganelle/files/14154656/slimmed_assembly_graph.slim.log.txt)

**Comment by JianjunJin** [comment]
@louisvant 
Thanks for the feedback.
Did you see valid blast hits in the temp files?

**Comment by louisvant** [comment]
> @louisvant Thanks for the feedback. Did you see valid blast hits in the temp files?

Thank u, there are only 5 files in the folder, and there is only a temp blast file in this folder. 
Here is the file: 
<img width="283" alt="2024-02-04 111924" src="https://github.com/Kinggerm/GetOrganelle/assets/109279658/d77e7221-31d9-481c-8f02-6745597975aa">
[slimmed_assembly_graph.Temp.blast_in.txt](https://github.com/Kinggerm/GetOrganelle/files/14155336/slimmed_assembly_graph.Temp.blast_in.txt)

**Comment by SamCT** [comment]
Also wanted to chime in here saying I received the same error with a hifiasm p_utg. However, the log file(s) are not very informative.
