### ISSUE TITLE
Problems with gfa processing

### ISSUE THREAD

**Issue by Hoberti** [Kinggerm/GetOrganelle#265]
Describe the bug
I am using getorganelle for obtaining a circular mitochondria and I am getting this message. The gfa is from a canu assembly. Could you help me please? What could be wrong in the gfa? 

2023-05-10 17:12:23,670 - ERROR:
Traceback (most recent call last):
  File "getorganelle/bin/slim_graph.py", line 976, in main
    this_assembly = Assembly(graph_file=fas_file, min_cov=options.min_depth, max_cov=options.max_depth)
  File "getorganelle/lib/python3.8/site-packages/GetOrganelleLib/assembly_parser.py", line 619, in __init__
    super(Assembly, self).__init__(graph_file=graph_file, min_cov=min_cov, max_cov=max_cov)
  File "getorganelle/lib/python3.8/site-packages/GetOrganelleLib/assembly_parser.py", line 258, in __init__
    self.parse_gfa(graph_file, min_cov=min_cov, max_cov=max_cov)
  File "/getorganelle/lib/python3.8/site-packages/GetOrganelleLib/assembly_parser.py", line 338, in parse_gfa
    raise ProcessingGraphFailed(vertex_name + " has unmatched sequence length as noted!")
GetOrganelleLib.assembly_parser.ProcessingGraphFailed: 'tig00000001 has unmatched sequence length as noted!'

2023-05-10 17:12:23,810 - ERROR:
Traceback (most recent call last):
  File "getorganelle/bin/get_organelle_from_assembly.py", line 1019, in main
    exit()
  File "getorganelle/lib/python3.8/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

Total cost 2.66 s

The following command was executed:
get_organelle_from_assembly.py -o getorgan -F embplant_mt -g Mito.unitigs.gfa

**Comment by JianjunJin** [comment]
Hi @Hoberti , Sorry for the long delay. The support for *.gfa files has been tested for `SPAdes`, `flye`, and `hifiasm`, as well as tools that produce a similar style of gfa. I just checked a `*.unitigs.gfa` file produced by `canu` on my hand and found it contains no sequence, while the sequences were stored in a concomitant `*.unitigs.fasta` file. Something must be done to accommodate this style of `gfa`+`fasta`. I will leave it open until I add the feature. But it won't be very fast bc I'm swamped by other projects recently.  For now, you may try `flye` instead.
Thank you for posting this issue!
