### ISSUE TITLE
Empty fileIp.plastome/check/1/check_1

### ISSUE THREAD

**Issue by zhyx6511** [Kinggerm/GetOrganelle#295]
Describe the bug
I am using getorganelle for assembly of chroloplast genome and I am getting this error message. I  have used the second generation pair-end reads, 2500000 reads,  Could you help me please?

2023-09-30 15:42:55,332 - ERROR: 
Traceback (most recent call last):
  File "/root/miniconda3/envs/Organelle/bin/get_organelle_from_reads.py", line 3886, in main
    random_seed=options.random_seed, verbose_log=options.verbose_log, log_handler=log_handler)
  File "/root/miniconda3/envs/Organelle/bin/get_organelle_from_reads.py", line 1078, in estimate_maximum_n_reads_using_mapping
    raise ValueError("Empty file" + check_fq + "\n"
ValueError: Empty fileIp.plastome/check/1/check_1
Please check the legality and integrity of your input reads!
Total cost 2.66 s

The following command was executed:
get_organelle_from_reads.py -1 ip_r1.fq.gz -2 ip_r2.fq.gz -t 70 -o Ip.plastome -F embplant_pt -R 15

**Comment by JianjunJin** [comment]
Please follow the issue template to provide adequate information.
