### ISSUE TITLE
ERROR: slimming the pre-assembled graph failed

### ISSUE THREAD

**Issue by winni-liu** [Kinggerm/GetOrganelle#297]
**the log is:** 

`GetOrganelle v1.7.7.0

get_organelle_from_reads.py assembles organelle genomes from genome skimming data.
Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.

Python 3.10.13 (main, Sep 11 2023, 13:21:10) [GCC 11.2.0]
PLATFORM: Linux bio21-Super-Server 5.15.0-86-generic #96~20.04.1-Ubuntu SMP Thu Sep 21 13:23:37 UTC 2023 x86_64 x86_64
PYTHON LIBS: GetOrganelleLib 1.7.7.0; numpy 1.26.0; sympy 1.11.1; scipy 1.11.3
DEPENDENCIES: Bowtie2 2.5.2; SPAdes 3.15.5; Blast version
GETORG_PATH=/home/data/t190452/.GetOrganelle
SEED  DB: embplant_pt 0.0.1; embplant_mt 0.0.1
LABEL DB: embplant_pt 0.0.1; embplant_mt 0.0.1
WORKING DIR: /home/data/t190452/project/egg/01.chloroplast/02.assemble/test
/home/data/t190452/biosoftware/bin/get_organelle_from_reads.py -1 Arabidopsis_simulated.1.fq.gz -2 Arabidopsis_simulated.2.fq.gz -t 1 -o Arabidopsis_simulated.plastome -F embplant_pt -R 10

2023-10-30 16:19:07,086 - INFO: Pre-reading fastq ...
2023-10-30 16:19:07,086 - INFO: Estimating reads to use ... (to use all reads, set '--reduce-reads-for-coverage inf --max-reads inf')
2023-10-30 16:19:07,177 - INFO: Estimating reads to use finished.
2023-10-30 16:19:07,177 - INFO: Unzipping reads file: Arabidopsis_simulated.1.fq.gz (8796915 bytes)
2023-10-30 16:19:07,395 - INFO: Unzipping reads file: Arabidopsis_simulated.2.fq.gz (9067061 bytes)
2023-10-30 16:19:07,579 - INFO: Counting read qualities ...
2023-10-30 16:19:07,686 - INFO: Identified quality encoding format = Illumina 1.8+
2023-10-30 16:19:07,686 - INFO: Phred offset = 33
2023-10-30 16:19:07,688 - INFO: Trimming bases with qualities (0.00%): 33..33  !
2023-10-30 16:19:07,743 - INFO: Mean error rate = 0.0019
2023-10-30 16:19:07,744 - INFO: Counting read lengths ...
2023-10-30 16:19:07,888 - INFO: Mean = 150.0 bp, maximum = 150 bp.
2023-10-30 16:19:07,888 - INFO: Reads used = 91563+91563
2023-10-30 16:19:07,888 - INFO: Pre-reading fastq finished.

2023-10-30 16:19:07,888 - INFO: Making seed reads ...
2023-10-30 16:19:07,888 - INFO: Seed bowtie2 index existed!
2023-10-30 16:19:07,888 - INFO: Mapping reads to seed bowtie2 index ...
2023-10-30 16:19:18,263 - INFO: Mapping finished.
2023-10-30 16:19:18,264 - INFO: Seed reads made: Arabidopsis_simulated.plastome/seed/embplant_pt.initial.fq (14144302 bytes)
2023-10-30 16:19:18,264 - INFO: Making seed reads finished.

2023-10-30 16:19:18,264 - INFO: Checking seed reads and parameters ...
2023-10-30 16:19:18,264 - INFO: The automatically-estimated parameter(s) do not ensure the best choice(s).
2023-10-30 16:19:18,264 - INFO: If the result graph is not a circular organelle genome,
2023-10-30 16:19:18,265 - INFO:   you could adjust the value(s) of '-w'/'-R' for another new run.
2023-10-30 16:19:21,030 - INFO: Pre-assembling mapped reads ...
2023-10-30 16:19:28,858 - ERROR: slimming the pre-assembled graph failed.
2023-10-30 16:19:28,868 - INFO: Pre-assembling mapped reads finished.
2023-10-30 16:19:28,868 - INFO: Estimated embplant_pt-hitting base-coverage = 38.05
2023-10-30 16:19:29,112 - INFO: Estimated word size(s): 86
2023-10-30 16:19:29,113 - INFO: Setting '-w 86'
2023-10-30 16:19:29,113 - INFO: Setting '--max-extending-len inf'
2023-10-30 16:19:29,236 - INFO: Checking seed reads and parameters finished.

2023-10-30 16:19:29,236 - INFO: Making read index ...
2023-10-30 16:19:30,641 - INFO: 178623 candidates in all 183126 reads
2023-10-30 16:19:30,641 - INFO: Pre-grouping reads ...
2023-10-30 16:19:30,641 - INFO: Setting '--pre-w 86'
2023-10-30 16:19:30,659 - INFO: 4074/4074 used/duplicated
2023-10-30 16:19:31,046 - INFO: 427 groups made.
2023-10-30 16:19:31,060 - INFO: Making read index finished.

2023-10-30 16:19:31,060 - INFO: Extending ...
2023-10-30 16:19:31,060 - INFO: Adding initial words ...
2023-10-30 16:19:33,508 - INFO: AW 1199618
2023-10-30 16:19:35,660 - INFO: Round 1: 178623/178623 AI 40466 AW 1215886
2023-10-30 16:19:36,614 - INFO: Round 2: 178623/178623 AI 40485 AW 1216028
2023-10-30 16:19:37,545 - INFO: Round 3: 178623/178623 AI 40485 AW 1216028
2023-10-30 16:19:37,545 - INFO: No more reads found and terminated ...
2023-10-30 16:19:37,913 - INFO: Extending finished.

2023-10-30 16:19:38,029 - INFO: Separating extended fastq file ...
2023-10-30 16:19:38,107 - INFO: Setting '-k 21,55,85,115'
2023-10-30 16:19:38,107 - INFO: Assembling using SPAdes ...
2023-10-30 16:19:38,110 - INFO: spades.py -t 1  --phred-offset 33 -1 Arabidopsis_simulated.plastome/extended_1_paired.fq -2 Arabidopsis_simulated.plastome/extended_2_paired.fq --s1 Arabidopsis_simulated.plastome/extended_1_unpaired.fq --s2 Arabidopsis_simulated.plastome/extended_2_unpaired.fq -k 21,55,85,115 -o Arabidopsis_simulated.plastome/extended_spades
2023-10-30 16:19:58,394 - INFO: Insert size = 499.355, deviation = 9.90921, left quantile = 487, right quantile = 512
2023-10-30 16:19:58,395 - INFO: Assembling finished.

2023-10-30 16:19:59,283 - ERROR: Slimming Arabidopsis_simulated.plastome/extended_spades/K115/assembly_graph.fastg failed. Please check Arabidopsis_simulated.plastome/extended_spades/K115/slim.log.txt for details.
2023-10-30 16:19:59,283 - ERROR: No valid assembly graph found!
2023-10-30 16:19:59,283 - WARNING: This might due to a damaged dependency, to unreasonable seed/parameter choices, or to a bug.
2023-10-30 16:19:59,283 - INFO: Please first search similar issues at https://github.com/Kinggerm/GetOrganelle/issues, then leave your message following the same issue, or open an issue at https://github.com/Kinggerm/GetOrganelle/issues if it is new, Please always attach the get_org.log.txt file.

Total cost 53.25 s
Thank you!`

**and the Arabidopsis_simulated.plastome/extended_spades/K115/slim.log.txt:**
`2023-10-30 16:19:59,190 - INFO: Slimming file 1/1: Arabidopsis_simulated.plastome/extended_spades/K115/assembly_graph.fastg
2023-10-30 16:19:59,192 - INFO: Parsing input finished.
2023-10-30 16:19:59,193 - INFO: Preparing fasta file finished.
2023-10-30 16:19:59,193 - INFO: Executing BLAST to /home/data/t190452/.GetOrganelle/LabelDatabase/embplant_pt ...
2023-10-30 16:19:59,193 - INFO: Executing BLAST ...
2023-10-30 16:19:59,198 - INFO: Executing BLAST finished.
2023-10-30 16:19:59,198 - INFO: Executing BLAST to /home/data/t190452/.GetOrganelle/LabelDatabase/embplant_pt finished.
2023-10-30 16:19:59,198 - ERROR: blastn was not properly configured.
2023-10-30 16:19:59,199 - ERROR:

2023-10-30 16:19:59,199 - ERROR: Slimming file 1/1: Arabidopsis_simulated.plastome/extended_spades/K115/assembly_graph.fastg failed!

2023-10-30 16:19:59,199 - ERROR:
Traceback (most recent call last):
  File "/home/data/t190452/biosoftware/GetOrganelle-1.7.7.0/Utilities/slim_graph.py", line 509, in blast_and_call_names
    blast_out_lines = open(out_file, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/t190452/project/egg/01.chloroplast/02.assemble/test/Arabidopsis_simulated.plastome/extended_spades/K115/assembly_graph.fastg.Temp.blast_in'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/data/t190452/biosoftware/GetOrganelle-1.7.7.0/Utilities/slim_graph.py", line 1070, in main
    raise e
  File "/home/data/t190452/biosoftware/GetOrganelle-1.7.7.0/Utilities/slim_graph.py", line 1016, in main
    in_names = blast_and_call_names(fasta_file=blast_fas, index_files=include_indices,
  File "/home/data/t190452/biosoftware/GetOrganelle-1.7.7.0/Utilities/slim_graph.py", line 515, in blast_and_call_names
    raise EnvironmentError
OSError`

**Comment by JianjunJin** [comment]
Sorry for the late reply. Hope you have solved it.
