### ISSUE TITLE
ERROR: slimming the pre-assembled graph failed

### ISSUE THREAD

**Issue by MarjaHei** [Kinggerm/GetOrganelle#311]
Hi!

I'm trying to assemble a mitogenome of a peracarid crustacean but encountered a problem that I don't know how to solve. Any help in troubleshooting would be greatly appreciated. 

2024-02-05 19:14:54,676 - INFO: Checking seed reads and parameters ...
2024-02-05 19:14:54,676 - INFO: The automatically-estimated parameter(s) do not ensure the best choice(s).
2024-02-05 19:14:54,676 - INFO: If the result graph is not a circular organelle genome, 
2024-02-05 19:14:54,676 - INFO:   you could adjust the value(s) of '-w'/'-R' for another new run.
2024-02-05 19:14:55,566 - INFO: Pre-assembling mapped reads ...
2024-02-05 19:15:18,247 - ERROR: slimming the pre-assembled graph failed.
2024-02-05 19:15:18,290 - INFO: Pre-assembling mapped reads finished.
2024-02-05 19:15:18,290 - INFO: Estimated animal_mt-hitting base-coverage = 0.00
2024-02-05 19:15:18,499 - ERROR: 
Traceback (most recent call last):
  File "/net/software/testing/software/GetOrganelle/1.7.6.1-foss-2021b/bin/get_organelle_from_reads.py", line 3965, in main
    check_parameters(word_size=word_size,
  File "/net/software/testing/software/GetOrganelle/1.7.6.1-foss-2021b/bin/get_organelle_from_reads.py", line 1643, in check_parameters
    word_size = estimate_word_size(
  File "/net/software/testing/software/GetOrganelle/1.7.6.1-foss-2021b/bin/get_organelle_from_reads.py", line 1247, in estimate_word_size
    estimated_word_size = int(read_length * (1 - word_cov / base_cov)) + 1
ZeroDivisionError: float division by zero

Thanks,
Marja

**Comment by MarjaHei** [comment]
Sure, here is the complete log file.

GetOrganelle v1.7.6.1

get_organelle_from_reads.py assembles organelle genomes from genome skimming data.
Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.

Python 3.9.6 (default, Oct  6 2021, 13:38:06)  [GCC 11.2.0]
PLATFORM: Linux ac0076 4.18.0-513.11.1.el8_9.x86_64 #1 SMP Wed Jan 10 22:58:54 UTC 2024 x86_64 x86_64
PYTHON LIBS: GetOrganelleLib 1.7.6.1; numpy 1.21.3; sympy 1.9; scipy 1.7.1; psutil 5.8.0
DEPENDENCIES: Bowtie2 2.4.4; SPAdes 3.15.3; Blast 2.12.0; Bandage xcb.
GETORG_PATH=/net/pr2/datasets/GetOrganelle
SEED  DB: animal_mt customized
LABEL DB: animal_mt 0.0.1
WORKING DIR: /net/ascratch/people/plgmarja0110
/net/software/testing/software/GetOrganelle/1.7.6.1-foss-2021b/bin/get_organelle_from_reads.py -1 ./trimmed/Adapters_only/trimmed_adapters_only-A3_S9_merged_R1.fastq.gz -2 ./trimmed/Adapters_only/trimmed_adapters_only-A3_S9_merged_R2.fastq.gz -t 8 -R 10 -k 21,45,65,85,105 -F animal_mt -o peraeospinosus_2_mt_out

2024-02-05 11:59:14,982 - INFO: Pre-reading fastq ...
2024-02-05 11:59:14,983 - INFO: Estimating reads to use ... (to use all reads, set '--reduce-reads-for-coverage inf --max-reads inf')
2024-02-05 11:59:15,114 - INFO: Tasting 100000+100000 reads ...
2024-02-05 11:59:30,632 - INFO: Tasting 500000+500000 reads ...
2024-02-05 12:00:57,168 - INFO: Tasting 2500000+2500000 reads ...
2024-02-05 12:07:27,914 - INFO: Tasting 12500000+12500000 reads ...
2024-02-05 12:38:17,390 - INFO: Estimating reads to use finished.
2024-02-05 12:38:17,523 - INFO: Unzipping reads file: ./trimmed/Adapters_only/trimmed_adapters_only-A3_S9_merged_R1.fastq.gz (39462339584 bytes)
2024-02-05 12:50:43,382 - INFO: Unzipping reads file: ./trimmed/Adapters_only/trimmed_adapters_only-A3_S9_merged_R2.fastq.gz (41033488680 bytes)
2024-02-05 13:03:26,641 - INFO: Counting read qualities ...
2024-02-05 13:03:26,934 - INFO: Identified quality encoding format = Sanger
2024-02-05 13:03:26,934 - INFO: Phred offset = 33
2024-02-05 13:03:26,935 - INFO: Trimming bases with qualities (0.00%): 33..33  !
2024-02-05 13:03:26,996 - INFO: Mean error rate = 0.0073
2024-02-05 13:03:26,997 - INFO: Counting read lengths ...
2024-02-05 13:17:17,748 - INFO: Mean = 161.0 bp, maximum = 251 bp.
2024-02-05 13:17:17,749 - INFO: Reads used = 300000000+300000000
2024-02-05 13:17:17,749 - INFO: Pre-reading fastq finished.

2024-02-05 13:17:17,749 - INFO: Making seed reads ...
2024-02-05 13:17:17,937 - INFO: Setting '-s peraeospinosus_2_mt_out/seed/animal_mt.fasta'
2024-02-05 13:17:17,961 - INFO: Making seed - bowtie2 index ...
2024-02-05 13:17:22,461 - INFO: Making seed - bowtie2 index finished.
2024-02-05 13:17:22,462 - INFO: Mapping reads to seed bowtie2 index ...
2024-02-05 19:14:54,581 - INFO: Mapping finished.
2024-02-05 19:14:54,676 - INFO: Seed reads made: peraeospinosus_2_mt_out/seed/animal_mt.initial.fq (51481 bytes)
2024-02-05 19:14:54,676 - INFO: Making seed reads finished.

2024-02-05 19:14:54,676 - INFO: Checking seed reads and parameters ...
2024-02-05 19:14:54,676 - INFO: The automatically-estimated parameter(s) do not ensure the best choice(s).
2024-02-05 19:14:54,676 - INFO: If the result graph is not a circular organelle genome, 
2024-02-05 19:14:54,676 - INFO:   you could adjust the value(s) of '-w'/'-R' for another new run.
2024-02-05 19:14:55,566 - INFO: Pre-assembling mapped reads ...
2024-02-05 19:15:18,247 - ERROR: slimming the pre-assembled graph failed.
2024-02-05 19:15:18,290 - INFO: Pre-assembling mapped reads finished.
2024-02-05 19:15:18,290 - INFO: Estimated animal_mt-hitting base-coverage = 0.00
2024-02-05 19:15:18,499 - ERROR: 
Traceback (most recent call last):
  File "/net/software/testing/software/GetOrganelle/1.7.6.1-foss-2021b/bin/get_organelle_from_reads.py", line 3965, in main
    check_parameters(word_size=word_size,
  File "/net/software/testing/software/GetOrganelle/1.7.6.1-foss-2021b/bin/get_organelle_from_reads.py", line 1643, in check_parameters
    word_size = estimate_word_size(
  File "/net/software/testing/software/GetOrganelle/1.7.6.1-foss-2021b/bin/get_organelle_from_reads.py", line 1247, in estimate_word_size
    estimated_word_size = int(read_length * (1 - word_cov / base_cov)) + 1
ZeroDivisionError: float division by zero

Total cost 26186.60 s

##############################
For trouble-shooting, please 
Firstly, check https://github.com/Kinggerm/GetOrganelle/wiki/FAQ
Secondly, check if there are open/closed issues related at https://github.com/Kinggerm/GetOrganelle/issues
If your problem was still not solved, 
  please open an issue at https://github.com/Kinggerm/GetOrganelle/issues
  please provide the get_org.log.txt and the assembly_graph.fastg.*.fastg file(s) (can be visualized as *.png to protect your data privacy) if possible!

**Comment by JianjunJin** [comment]
Apologies for the delayed response. The issue appears to stem from either insufficient target coverage or an inadequate seed database. I recommend utilizing a custom database (see [here](https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#how-to-assemble-a-target-organelle-genome-using-my-own-reference) for how to make) from closely related taxa.

On my end, efforts will be made to address this in the upcoming release by refining the code to mitigate such errors and provide more instructive guidance within the log. Thanks again for reporting it.

Let me know your updates.

**Comment by MarjaHei** [comment]
Thanks for getting back to me. I will try with a custom database then.

**Comment by JianjunJin** [comment]
Did the issue persist?
