### ISSUE TITLE
An input/output error while running Getorganelle

### ISSUE THREAD

**Issue by yinuosun986** [Kinggerm/GetOrganelle#328]
I have encountered an error while running Getorganelle on my Linux server, here is my log file:

2024-04-30 09:35:54,350 - INFO: Checking seed reads and parameters ...
2024-04-30 09:35:54,351 - INFO: The automatically-estimated parameter(s) do not ensure the best choice(s).
2024-04-30 09:35:54,352 - INFO: If the result graph is not a circular organelle genome, 
2024-04-30 09:35:54,353 - INFO:   you could adjust the value(s) of '-w'/'-R' for another new run.
2024-04-30 09:35:57,552 - INFO: Pre-assembling mapped reads ...
2024-04-30 09:36:04,887 - INFO: Pre-assembling mapped reads finished.
2024-04-30 09:36:04,888 - INFO: Estimated animal_mt-hitting base-coverage = 1057.38
2024-04-30 09:36:05,113 - INFO: Reads reduced to = 2168135+2168135
2024-04-30 09:36:05,126 - INFO: Adjusting expected animal_mt base coverage to 500.00
2024-04-30 09:36:05,127 - INFO: Estimated word size(s): 119
2024-04-30 09:36:05,128 - INFO: Setting '-w 119'
2024-04-30 09:36:05,129 - INFO: Setting '--max-extending-len inf'
2024-04-30 09:36:05,245 - INFO: Checking seed reads and parameters finished.

2024-04-30 09:36:05,258 - INFO: Making read index ...
2024-04-30 09:36:05,261 - ERROR: 
Traceback (most recent call last):
  File "/apps/miniforge3/envs/mito_assemble/bin/get_organelle_from_reads.py", line 3988, in main
    fq_info_in_memory = make_read_index(original_fq_files, direction_according_to_user_input,
  File "/apps/miniforge3/envs/mito_assemble/bin/get_organelle_from_reads.py", line 2015, in make_read_index
    sys.stdout.flush()
OSError: [Errno 5] Input/output error

Total cost 1259.42 s

and the version of my GetOrganelle is v1.7.7.0, and here is my commands:

get_organelle_from_reads.py -1 $fq1 -2 $fq2 -t 4 -o $out_dir -F animal_mt -R 20 -s $fasta

the path of two pair-ended files and seed file is correct, thanks in advance if anyone know the solution!

**Comment by yinuosun986** [comment]
I find the solution, i used another sequence as seed file, and it can run normally
