### ISSUE TITLE
TypeError: can't convert complex to int.

### ISSUE THREAD

**Issue by allen-zhan340** [Kinggerm/GetOrganelle#333]
Hi!

I'm trying to assemble a mitogenome of Panax notoginseng(SRR16979610) but encountered a problem that I don't know how to solve. Any help in troubleshooting would be greatly appreciated.

The problem follows:
**Describe the bug**
2024-05-27 11:06:53,271 - INFO: Estimated embplant_mt-hitting base-coverage = 7.00
2024-05-27 11:07:01,873 - ERROR:
Traceback (most recent call last):
  File "/home/zhanpc/.conda/envs/plan_assembly/bin/get_organelle_from_reads.py", line 3990, in main
    resume=resume, verbose_log=verb_log, zip_files=options.zip_files)
  File "/home/zhanpc/.conda/envs/plan_assembly/bin/get_organelle_from_reads.py", line 1655, in check_parameters
    wc_bc_ratio_constant=wc_bc_ratio_constant, organelle_type=organelle_types[go_type])
  File "/home/zhanpc/.conda/envs/plan_assembly/bin/get_organelle_from_reads.py", line 1254, in estimate_word_size
    estimated_word_size = int(read_length * (1 - word_cov / base_cov)) + 1
TypeError: can't convert complex to int

Total cost 5270.64 s

**To Reproduce**
- [ ] COMMAND: get_organelle_from_reads.py -u SRR16979610.fastq -o mitochondria_output -t 40 -R 15 -k 21,45,65,85,105 -P 1000000 -F embplant_mt

**Additional context**
the log files:

[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/15451061/get_org.log.txt)

**Comment by JianjunJin** [comment]
@allen-zhan340 
```
2024-05-27 09:44:07,131 - INFO: Identified quality encoding format = Solexa
2024-05-27 09:44:07,131 - INFO: Phred offset = 64
2024-05-27 09:44:07,132 - WARNING: Max quality score '{'(123:59) in your fastq file exceeds the usual range (59, 104)
2024-05-27 09:44:07,132 - WARNING: Min quality score '"'(34:-30) in your fastq file is under the usual lower boundary (59, 104)
2024-05-27 09:44:07,193 - INFO: Resetting '--min-quality-score -29'
2024-05-27 09:44:07,193 - INFO: Trimming bases with qualities (0.10%): 34..34  "
2024-05-27 09:44:10,823 - INFO: Mean error rate = 0.8837
2024-05-27 09:44:10,831 - INFO: Counting read lengths ...
2024-05-27 09:44:18,227 - INFO: Mean = 8808.1 bp, maximum = 82354 bp.
2024-05-27 09:44:18,227 - INFO: Reads used = 652246
2024-05-27 09:44:18,227 - INFO: Pre-reading fastq finished.
```

Are you using long read sequencing data? Current GetOrganelle versions doesn't support long read input.
