### ISSUE TITLE
Error with running SPAdes: == Error ==  exception caught: <class 'AttributeError'>

### ISSUE THREAD

**Issue by oddguyeee** [Kinggerm/GetOrganelle#345]
**First check**
- [ ] I used the GitHub search to find a similar issue or discussion and didn't find it.
- [ ] I searched [GetOrganelle.wiki](https://github.com/Kinggerm/GetOrganelle/wiki) context, especially the [FAQ](https://github.com/Kinggerm/GetOrganelle/wiki/FAQ) and browsed the [examples](https://github.com/Kinggerm/GetOrganelle/wiki/Examples) to confirm it is unexpected to happen.
- [ ] I have updated GetOrganelle to the latest released version [![GitHub release](https://img.shields.io/github/release/Kinggerm/GetOrganelle.svg)](https://GitHub.com/Kinggerm/GetOrganelle/releases/)

Please ask questions in the [Question in GitHub Discussions](https://github.com/Kinggerm/GetOrganelle/discussions/categories/q-a) unless it is a feature request or bug report.

Hi,

I am trying use HiFi reads to assembly plastid genome, and encountered the error:
```
# get_org.log.txt
...
2024-08-22 18:28:54,304 - INFO: Setting '-k 21,45,65,85,105'
2024-08-22 18:28:54,304 - INFO: Assembling using SPAdes ...
2024-08-22 18:28:54,354 - INFO: spades.py -t 20  --phred-offset 33 --s1 PF_CP_D01/extended_1.fq -k 21,45,65,85,105 -o PF_CP_D01/extended_spades
2024-08-23 20:24:53,099 - ERROR: Error with running SPAdes: == Error ==  exception caught: <class 'AttributeError'>
2024-08-23 20:24:53,205 - ERROR: Assembling failed.

# spades.log
...
===== Assembling started.

'dict' object has no attribute 'add'
Traceback (most recent call last):
  File "/nfs_fs/nfs3/jiezhang/miniconda3/envs/getorganelle/bin/spades.py", line 881, in main
    used_K = spades_logic.run_spades(tmp_configs_dir, bin_home, spades_cfg, dataset_data, ext_python_modules_home, log)
  File "/nfs_fs/nfs3/jiezhang/miniconda3/envs/getorganelle/share/spades-3.13.1-0/share/spades/spades_pipeline/spades_logic.py", line 307, in run_spades
    run_iteration(configs_dir, execution_home, cfg, log, K, None, False)
  File "/nfs_fs/nfs3/jiezhang/miniconda3/envs/getorganelle/share/spades-3.13.1-0/share/spades/spades_pipeline/spades_logic.py", line 184, in run_iteration
    dir_util.copy_tree(os.path.join(configs_dir, "debruijn"), dst_configs, preserve_times=False)
  File "/nfs_fs/nfs3/jiezhang/miniconda3/envs/getorganelle/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 146, in copy_tree
    mkpath(dst, verbose=verbose)
  File "/nfs_fs/nfs3/jiezhang/miniconda3/envs/getorganelle/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 82, in mkpath
    _path_created.add(abs_head)
AttributeError: 'dict' object has no attribute 'add'


== Error ==  exception caught: <class 'AttributeError'>

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.
```
I am not sure that this error was caused by data or environment incompatible, and I add the main logs and the cmd below， thank you very much!
```sh
get_organelle_from_reads.py -u ../PF_HiFi_fa/PF_hifi_read_D01.fastq.gz -t 20 -o PF_CP_D01 -R 15 -k 21,45,65,85,105 -F embplant_pt
```
[get_org.log.txt](https://github.com/user-attachments/files/16735009/get_org.log.txt)
[params.txt](https://github.com/user-attachments/files/16735010/params.txt)
[spades.log](https://github.com/user-attachments/files/16735011/spades.log)

**Comment by HannahRH98** [comment]
I have had the same error so any help would be appreciated!

**Comment by booknary** [comment]
same as yours! idk what happened to it

**Comment by oddguyeee** [comment]
@HannahRH98 @booknary:

The problem is still existing, I guess it is related with data type. Because It is well work when I run same cmd with NGS data, but not well done with HiFi reads.  
﻿
If you find the solution would be appreciated!

**Comment by HannahRH98** [comment]
I am using NGS data too and it's not working. It seems to be SPAdes error.

**Comment by oddguyeee** [comment]
@HannahRH98 ,

Maybe you can try re-install the getorganelle and it's dependency.

**Comment by HannahRH98** [comment]
Already tried that. Unfortunately, it didn't work.

**Comment by yoyootato** [comment]
I also have the same problem!

**Comment by HannahRH98** [comment]
Hopefully, it can get sorted soon!

**Comment by SadiaKamalMysha** [comment]
Same thing happened to me! I tried assembling the genome of _L. wurdemanni_ the following error keeps showing...

Checking seed reads and parameters ...
The automatically-estimated parameter(s) do not ensure the best choice(s).
If the result graph is not a circular organelle genome,
you could adjust the value(s) of '-w'/'-R' for another new run.
Pre-assembling mapped reads ...
Retrying with more reads ..
ERROR: Error with running SPAdes: == Error ==  exception caught: <class 'AttributeError'>
2024-09-19 22:02:08,322 - WARNING: Pre-assembling failed. The estimations for animal_mt-hitting base-coverage and word size may be misleading.
Estimated animal_mt-hitting base-coverage = 69.25
Estimated word size(s): 141
Setting '-w 141'
Setting '--max-extending-len inf'
Checking seed reads and parameters finished.
...............
Separating extended fastq file ...
Setting '-k 21,55,85,115'
Assembling using SPAdes ...
spades.py -t 11  --phred-offset 33 -1 Lysmata.mitogenome4/extended_1_paired.fq -2 Lysmata.mitogenome4/extended_2_paired.fq --s1 Lysmata.mitogenome4/extended_1_unpaired.fq --s2 Lysmata.mitogenome4/extended_2_unpaired.fq -k 21,55,85,115 -o Lysmata.mitogenome4/extended_spades
ERROR: Error with running SPAdes: == Error ==  exception caught: <class 'AttributeError'>
ERROR: Assembling failed.

**Comment by Aravinda89** [comment]
Installing python=3.8 with spades=3.15.5 worked
