### ISSUE TITLE
get_organelle_from_assembly.py

### ISSUE THREAD

**Issue by LucaD91** [Kinggerm/GetOrganelle#48]
hi everyone, i'm trying to evaluate the mithocondrial DNA of my sample (fusarium sp.);
i performed the assembly with flye tool on galaxy.eu and use the fastg file produced by the tool.
i always get this error and i can't go on, can you help me? what i'm doing wrong?

HERE THE LOG.TXT FILE:
GetOrganelle v1.7.1a

get_organelle_from_assembly.py isolates organelle genomes from assembly graph.
Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.

Python 3.8.2 (default, Mar 13 2020, 10:14:16)  [GCC 9.3.0]
PYTHON LIBS: GetOrganelleLib 1.7.1a; numpy 1.17.4; sympy 1.5.1; scipy 1.3.3
DEPENDENCIES: Blast 2.9.0
LABEL DB: fungus_mt 0.0.0
WORKING DIR: /home/luca/GetOrganelle
get_organelle_from_assembly.py -F fungus_mt -g seitu.fastg -o risultati/mitoF31

2020-08-07 09:00:50,485 - INFO: Processing assembly graph ...
2020-08-07 09:00:51,011 - INFO: Processing assembly graph finished.

2020-08-07 09:00:51,011 - INFO: Slimming assembly graph ...
2020-08-07 09:00:51,053 - INFO: Slimming risultati/mitoF31/initial_assembly_graph.fastg finished!
2020-08-07 09:00:51,053 - ERROR: 
Traceback (most recent call last):
  File "get_organelle_from_assembly.py", line 988, in main
    if os.path.getsize(slimmed_graph_file) == 0:
  File "/usr/lib/python3.8/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'risultati/mitoF31/slimmed_assembly_graph.fastg'

Total cost 3.71 s
Please email jinjianjun@mail.kib.ac.cn or jianjun.jin@columbia.edu if you find bugs!
Please provide me with the get_org.log.txt file!

THANK'S EVERYONE

**Comment by Kinggerm** [comment]
Apologize for the late reply. 
Could you add --verbose to you command? Have you got a slim.log.txt file in the output directory?

**Comment by imogen-foote** [comment]
Did this ever get resolved? I am having a similar issue. It does not say that slimming failed so I'm having problems troubleshooting, but it doesn't seem to be saving the slimmed assembly graph so the next step can't find it (I think?)

2023-12-14 14:49:55,657 - INFO: Processing assembly graph ...
2023-12-14 14:50:02,194 - INFO: Processing assembly graph finished.

2023-12-14 14:50:02,195 - INFO: Slimming assembly graph ...
2023-12-14 14:50:10,665 - INFO: Slimming /nesi/nobackup/vuw03922/projects/AntipodeanAlbatross/data/Chapter3/mitogenome/blue-45G_q8_h50/initial_assembly_graph.gfa finished!
2023-12-14 14:50:10,667 - ERROR: 
Traceback (most recent call last):
  File "/nesi/project/vuw03922/bandage/bin/get_organelle_from_assembly.py", line 1021, in main
    if os.path.getsize(slimmed_graph_file) == 0:
  File "/nesi/project/vuw03922/bandage/lib/python3.9/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/nesi/nobackup/vuw03922/projects/AntipodeanAlbatross/data/Chapter3/mitogenome/blue-45G_q8_h50/slimmed_assembly_graph.gfa'

**Comment by JianjunJin** [comment]
Thanks for reaching out!
Could you add --verbose to your command? Have you got a slim.log.txt file in the output directory?

**Comment by imogen-foote** [comment]
Thanks @JianjunJin. Sorry I forgot to mention I tried it with --verbose in the command as per the previous suggestion and the above output is what that gave me. There is no slim.log.txt file in the output directory, only the get_org.log.txt and slimmed_assembly_graph.slim.log.txt that I included above.

**Comment by alistairhockey** [comment]
Would also appreciate this being solved. Having the exact same issue.

**Comment by JianjunJin** [comment]
Hi all, I cannot reproduce it from my side. But I would like to help.

Could you please test if `slim_graph.py -h` and `blastn -h` will be running correctly in your environment?

**Comment by alistairhockey** [comment]
Hi,

I think I solved the problem on my end: I had py scripts in my bin directory and in my conda environment. I removed the former and reinstalled getorganelle in the env and it worked.

Cheers,
Alistair
________________________________

**Comment by JianjunJin** [comment]
@alistairhockey Glad that you solved it! And thanks for letting me know.

**Comment by imogen-foote** [comment]
Hi @alistairhockey, thanks for the info. Would you mind giving me a little more specific detail on how you solved this? I'm relatively new to all this, so can't quite follow your directions above. I have the py scripts in my_env/bin/, but I'm not sure where else you meant you had them that you removed them from?

Thank you!! Much appreciated

**Comment by alistairhockey** [comment]
Hi @imogen-foote, I'd sugest the following:

1. Uninstall GetOrganelle and all .py scripts associated (e.g. get_organelle_from_reads.py).
2. Create a conda environment with GetOrganelle installed (conda create env *name* -c bioconda GetOrganelle)
3. Activate the conda environment.
4. Test it out! 

I found that having old GetOrganelle .py scripts in my /bin directory was causing the issue. Best to clean everything up and have the program running in a self-contained environment. 

Cheers.

**Comment by imogen-foote** [comment]
Thanks so much @alistairhockey. I think I was initially a bit confused because I didn't have GetOrganelles installed anywhere else, other than my conda environment. Anyway I also found a solution, which was to remove the conda environment and create it fresh, using mamba create (I got a bunch of dependency issues using conda but mamba seems to solve them) and installing both bandage and GetOrganelles at the time of creation (previously I created it with bandage and installed getorganelles after).
