### ISSUE TITLE
Error: Too few seed reads found!

### ISSUE THREAD

**Issue by Ruben9161** [Kinggerm/GetOrganelle#51]
Dear Jianjun Jin,

What should I do if I get this error: "Too few seed reads found"?
How do I change the _-s_ parameter?
I've tried the --max-reads parameter, but my files are of 387,936 reads after trimming and filtering and I got the same error after setting the --max-reads parameter.

Here's the log I got:

GetOrganelle v1.7.0

get_organelle_from_reads.py assembles organelle genomes from genome skimming data.
Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.

Python 3.8.5 | packaged by conda-forge | (default, Jul 22 2020, 17:10:02)  [Clang 10.0.0 ]
PYTHON LIBS: GetOrganelleLib 1.7.0; numpy 1.19.0; sympy 1.6.1; scipy 1.5.1
DEPENDENCIES: Bowtie2 2.4.1; SPAdes 3.12.0; Blast 2.6.0
SEED  DB: animal_mt 0.0.0
LABEL DB: animal_mt 0.0.0
WORKING DIR: /Users/getorganelle_doryctinae/CNIN4288
/opt/anaconda2/envs/getorganelle/bin/get_organelle_from_reads.py -1 CNIN4288_READ1.fq.gz -2 CNIN4288_READ2.fq.gz -o mtgenome_results -R 10 -k 21,45,65,85,105 -F animal_mt

2020-09-09 00:28:56,741 - INFO: Pre-reading fastq ...
2020-09-09 00:28:56,742 - INFO: Estimating reads to use ... (to use all reads, set '--reduce-reads-for-coverage inf')
2020-09-09 00:28:56,841 - INFO: Tasting 100000+100000 reads ...
2020-09-09 00:34:22,015 - INFO: Estimating reads to use finished.
2020-09-09 00:34:22,025 - INFO: Unzipping reads file: CNIN4288_READ1.fq.gz (29259677 bytes)
2020-09-09 00:34:22,606 - INFO: Unzipping reads file: CNIN4288_READ2.fq.gz (30627486 bytes)
2020-09-09 00:34:23,278 - INFO: Counting read qualities ...
2020-09-09 00:34:23,415 - INFO: Identified quality encoding format = Illumina 1.8+
2020-09-09 00:34:23,418 - INFO: Trimming bases with qualities (0.00%): 33..33  !
2020-09-09 00:34:23,462 - INFO: Mean error rate = 0.002
2020-09-09 00:34:23,463 - INFO: Counting read lengths ...
2020-09-09 00:34:24,483 - INFO: Mean = 150.0 bp, maximum = 150 bp.
2020-09-09 00:34:24,483 - INFO: Reads used = 387936+387936
2020-09-09 00:34:24,483 - INFO: Pre-reading fastq finished.

2020-09-09 00:34:24,483 - INFO: Making seed reads ...
2020-09-09 00:34:24,485 - INFO: Seed bowtie2 index existed!
2020-09-09 00:34:24,485 - INFO: Mapping reads to seed bowtie2 index ...
2020-09-09 00:34:42,693 - INFO: Mapping finished.
2020-09-09 00:34:42,693 - INFO: Seed reads made: mtgenome_results/seed/animal_mt.initial.fq (9223 bytes)
2020-09-09 00:34:42,694 - ERROR: Too few seed reads found! Please change your seed file (-s) or increase your data input (--max-reads/--reduce-reads-for-coverage)!
2020-09-09 00:34:42,694 - ERROR: 
Traceback (most recent call last):
  File "/opt/anaconda2/envs/getorganelle/bin/get_organelle_from_reads.py", line 3797, in main
    seed_fq, seed_sam, new_seed_f = making_seed_reads_using_mapping(
  File "/opt/anaconda2/envs/getorganelle/bin/get_organelle_from_reads.py", line 2931, in making_seed_reads_using_mapping
    exit()
  File "/opt/anaconda2/envs/getorganelle/lib/python3.8/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

Total cost 347.66 s
Please email jinjianjun@mail.kib.ac.cn or jianjun.jin@columbia.edu if you find bugs!
Please provide me with the get_org.log.txt file!
-------------------------------------------------------------------------------------------------------------------------------------------

Thanks in advance for your help!

Ruben.

**Comment by Kinggerm** [comment]
Hi Ruben,

I guess your raw data contains two few mitogenome reads. So "--max-reads/--reduce-reads-for-coverage" won't help because GetOrganelle wasn't reducing the reads.

You could try to input a mitogenome sequence of a closely-related species as the seed (-s sequence.fasta). But I don't think that's the key issue here.

I think the most probable solution is increasing your genome skimming dataset, which is currently only 116M basepairs and likely insufficient for most animal mt assembly.

Best,
Jianjun

**Comment by Ruben9161** [comment]
Hi Jianjun,

I will try with the -s parameter. I hope this could fix my problem.

Thanks a lot. I'll keep you updated!!!

Greetings,
Rubén.

**Comment by Ruben9161** [comment]
Dear Jianjun Jin,

Hi! It's me again, Rubén.

I was running a sample in GO and got these messages: 
"2020-09-26 14:55:33,237 - ERROR: Slimming mtgenome_results/filtered_spades/K65/assembly_graph.fastg failed.
 2020-09-26 14:55:34,165 - ERROR: Slimming mtgenome_results/filtered_spades/K45/assembly_graph.fastg failed."

What should I do to fix this problem?
Here's the log I got:


GetOrganelle v1.7.0

get_organelle_from_reads.py assembles organelle genomes from genome skimming data.
Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.

Python 3.8.5 | packaged by conda-forge | (default, Jul 22 2020, 17:10:02)  [Clang 10.0.0 ]
PYTHON LIBS: GetOrganelleLib 1.7.0; numpy 1.19.0; sympy 1.6.1; scipy 1.5.1
DEPENDENCIES: Bowtie2 2.4.1; SPAdes 3.12.0; Blast 2.6.0
SEED  DB: animal_mt 0.0.0
LABEL DB: animal_mt 0.0.0
WORKING DIR: /Users/alejandrozaldivar/getorganelle_doryctinae/BBP552
/opt/anaconda2/envs/getorganelle/bin/get_organelle_from_reads.py -1 BBP552_READ1.fastq.gz -2 BBP552_READ2.fastq.gz -o mtgenome_results -R 15 -k 21,45,65,85,105 -F animal_mt

2020-09-26 14:50:15,605 - INFO: Pre-reading fastq ...
2020-09-26 14:50:15,606 - INFO: Estimating reads to use ... (to use all reads, set '--reduce-reads-for-coverage inf')
2020-09-26 14:50:15,696 - INFO: Tasting 100000+100000 reads ...
2020-09-26 14:52:54,699 - INFO: Tasting 500000+500000 reads ...
2020-09-26 14:53:29,366 - INFO: Estimating reads to use finished.
2020-09-26 14:53:29,367 - INFO: Unzipping reads file: BBP552_READ1.fastq.gz (113972404 bytes)
2020-09-26 14:53:31,074 - INFO: Unzipping reads file: BBP552_READ2.fastq.gz (114963105 bytes)
2020-09-26 14:53:33,021 - INFO: Counting read qualities ...
2020-09-26 14:53:33,134 - INFO: Identified quality encoding format = Sanger
2020-09-26 14:53:33,135 - INFO: Trimming bases with qualities (0.00%): 33..33  !
2020-09-26 14:53:33,189 - INFO: Mean error rate = 0.0026
2020-09-26 14:53:33,191 - INFO: Counting read lengths ...
2020-09-26 14:53:36,376 - INFO: Mean = 118.6 bp, maximum = 125 bp.
2020-09-26 14:53:36,376 - INFO: Reads used = 1276687+1276687
2020-09-26 14:53:36,376 - INFO: Pre-reading fastq finished.

2020-09-26 14:53:36,376 - INFO: Making seed reads ...
2020-09-26 14:53:36,376 - INFO: Seed bowtie2 index existed!
2020-09-26 14:53:36,376 - INFO: Mapping reads to seed bowtie2 index ...
2020-09-26 14:54:24,324 - INFO: Mapping finished.
2020-09-26 14:54:24,324 - INFO: Seed reads made: mtgenome_results/seed/animal_mt.initial.fq (70772 bytes)
2020-09-26 14:54:24,324 - INFO: Making seed reads finished.

2020-09-26 14:54:24,324 - INFO: Checking seed reads and parameters ...
2020-09-26 14:54:24,324 - INFO: The automatically-estimated parameter(s) do not ensure the best choice(s).
2020-09-26 14:54:24,325 - INFO: If the result graph is not a circular organelle genome, 
2020-09-26 14:54:24,325 - INFO:   you could adjust the value(s) of '-w'/'-R' for another new run.
2020-09-26 14:54:26,488 - INFO: Pre-assembling mapped reads ...
2020-09-26 14:54:28,103 - ERROR: slimming the pre-assembled graph failed.
2020-09-26 14:54:28,108 - INFO: Pre-assembling mapped reads finished.
2020-09-26 14:54:28,108 - INFO: Estimated animal_mt-hitting base-coverage = 61.20
2020-09-26 14:54:28,250 - INFO: Estimated word size(s): 78
2020-09-26 14:54:28,250 - INFO: Setting '-w 78'
2020-09-26 14:54:28,250 - INFO: Setting '--max-extending-len inf'
2020-09-26 14:54:28,320 - INFO: Checking seed reads and parameters finished.

2020-09-26 14:54:28,320 - INFO: Making read index ...
2020-09-26 14:54:45,147 - INFO: 2020940 candidates in all 2553374 reads
2020-09-26 14:54:45,151 - INFO: Pre-grouping reads ...
2020-09-26 14:54:45,151 - INFO: Setting '--pre-w 78'
2020-09-26 14:54:45,403 - INFO: 200000/328283 used/duplicated
2020-09-26 14:54:58,502 - INFO: 9867 groups made.
2020-09-26 14:54:58,673 - INFO: Making read index finished.

2020-09-26 14:54:58,673 - INFO: Extending ...
2020-09-26 14:54:58,673 - INFO: Adding initial words ...
2020-09-26 14:54:58,677 - INFO: AW 2958
2020-09-26 14:55:07,803 - INFO: Round 1: 2020940/2020940 AI 50 AW 3288
2020-09-26 14:55:16,754 - INFO: Round 2: 2020940/2020940 AI 51 AW 3330
2020-09-26 14:55:25,741 - INFO: Round 3: 2020940/2020940 AI 51 AW 3330
2020-09-26 14:55:25,741 - INFO: No more reads found and terminated ...
2020-09-26 14:55:29,470 - INFO: Extending finished.

2020-09-26 14:55:29,512 - INFO: Separating filtered fastq file ... 
2020-09-26 14:55:29,513 - INFO: Setting '-k 21,45,65,85,105'
2020-09-26 14:55:29,514 - INFO: Assembling using SPAdes ...
2020-09-26 14:55:29,531 - INFO: spades.py -t 1  -1 mtgenome_results/filtered_1_paired.fq -2 mtgenome_results/filtered_2_paired.fq --s1 mtgenome_results/filtered_1_unpaired.fq --s2 mtgenome_results/filtered_2_unpaired.fq -k 21,45,65,85,105 -o mtgenome_results/filtered_spades
2020-09-26 14:55:31,890 - WARNING: SPAdes failed for '-k 85'!
2020-09-26 14:55:31,891 - WARNING: If you need result based on kmer=85 urgently, please check mtgenome_results/filtered_spades/spades.log
2020-09-26 14:55:31,891 - WARNING: GetOrganelle would continue to process results based on kmer=21,45,65.
2020-09-26 14:55:31,891 - INFO: Assembling finished with warnings.

2020-09-26 14:55:33,237 - ERROR: Slimming mtgenome_results/filtered_spades/K65/assembly_graph.fastg failed.
2020-09-26 14:55:34,165 - ERROR: Slimming mtgenome_results/filtered_spades/K45/assembly_graph.fastg failed.

Total cost 319.80 s
Thank you!


Thanks again for your help!

Your friend, Rubén.
