### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by bioramg** [Kinggerm/GetOrganelle#60]
Hello,
I am doing the plant mitochondrial genome assembly with the following commands. But I am getting a MemoryError issue. The same parameter has used for another mitochondrial genome assembly.

get_organelle_from_reads.py -1forward_paired.fq.gz -2 reverse_paired.fq.gz -o get_organelle/ -R 50 -P 1000000 -F embplant_mt --memory-save -w 95 --reduce-reads-for-coverage inf

log.txt

2020-11-18 09:37:23,901 - INFO: Counting read qualities ...
2020-11-18 09:37:24,110 - INFO: Identified quality encoding format = Illumina 1.8+
2020-11-18 09:37:24,111 - INFO: Trimming bases with qualities (0.00%): 33..33  !
2020-11-18 09:37:24,175 - INFO: Mean error rate = 0.0146
2020-11-18 09:37:24,176 - INFO: Counting read lengths ...
2020-11-18 09:41:21,922 - INFO: Mean = 151.0 bp, maximum = 151 bp.
2020-11-18 09:41:21,922 - INFO: Reads used = 72894963+72894963
2020-11-18 09:41:21,922 - INFO: Pre-reading fastq finished.

2020-11-18 09:41:21,922 - INFO: Making seed reads ...
2020-11-18 09:41:21,952 - INFO: Seed bowtie2 index existed!
2020-11-18 09:41:21,952 - INFO: Mapping reads to seed bowtie2 index ...
2020-11-18 10:14:08,892 - INFO: Mapping finished.
2020-11-18 10:14:08,893 - INFO: Seed reads made: ./../../raman/cma_mt/get_organelle/seed/embplant_mt.initial.fq (13572326 bytes)
2020-11-18 10:14:08,916 - INFO: Making seed reads finished.

2020-11-18 10:14:08,916 - INFO: Checking seed reads and parameters ...
2020-11-18 10:14:11,177 - INFO: Estimated embplant_mt-hitting base-coverage = 133.73
2020-11-18 10:14:11,665 - INFO: Setting '--max-extending-len inf'
2020-11-18 10:14:11,725 - INFO: Checking seed reads and parameters finished.

2020-11-18 10:14:11,725 - INFO: Making read index ...
2020-11-18 10:35:14,221 - INFO: Mem 19.971 G, 145789926 reads
2020-11-18 10:35:23,848 - INFO: Making read index finished.

2020-11-18 10:35:23,849 - INFO: Extending ...
2020-11-18 10:35:23,849 - INFO: Adding initial words ...
2020-11-18 10:35:25,549 - INFO: AW 1414726
2020-11-18 10:56:53,068 - INFO: Round 1: 145789926/145789926 AI 2547987 AW 20138238 Mem 4.131
2020-11-18 11:18:14,011 - INFO: Round 2: 145789926/145789926 AI 4002492 AW 29878554 Mem 5.502
2020-11-18 11:39:52,946 - INFO: Round 3: 145789926/145789926 AI 4844430 AW 49387612 Mem 9.185
2020-11-18 12:02:22,295 - INFO: Round 4: 145789926/145789926 AI 6248245 AW 85261724 Mem 16.365
2020-11-18 12:18:09,770 - ERROR: ound 5: 79960513/145789926 AI 8101461 AW 131499852
Traceback (most recent call last):
  File "/home/raman/anaconda3/bin/get_organelle_from_reads.py", line 3879, in main
  File "/home/raman/anaconda3/bin/get_organelle_from_reads.py", line 2371, in extending_no_lim
  File "/home/raman/anaconda3/bin/get_organelle_from_reads.py", line 2217, in <genexpr>
  File "/home/raman/anaconda3/lib/python3.7/codecs.py", line 322, in decode
MemoryError
--- Logging error ---
Traceback (most recent call last):
  File "/home/raman/anaconda3/bin/get_organelle_from_reads.py", line 3879, in main
  File "/home/raman/anaconda3/bin/get_organelle_from_reads.py", line 2371, in extending_no_lim
  File "/home/raman/anaconda3/bin/get_organelle_from_reads.py", line 2217, in <genexpr>
  File "/home/raman/anaconda3/lib/python3.7/codecs.py", line 322, in decode
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/raman/anaconda3/lib/python3.7/logging/__init__.py", line 1025, in emit
  File "/home/raman/anaconda3/lib/python3.7/logging/__init__.py", line 869, in format
  File "/home/raman/anaconda3/lib/python3.7/logging/__init__.py", line 610, in format
  File "/home/raman/anaconda3/lib/python3.7/logging/__init__.py", line 550, in formatTime
MemoryError
Call stack:
  File "/home/raman/anaconda3/bin/get_organelle_from_reads.py", line 4045, in <module>
  File "/home/raman/anaconda3/bin/get_organelle_from_reads.py", line 4036, in main
Message: ''
Arguments: ()
Traceback (most recent call last):
  File "/home/raman/anaconda3/bin/get_organelle_from_reads.py", line 3879, in main
    echo_step=echo_step, log_handler=log_handler)
  File "/home/raman/anaconda3/bin/get_organelle_from_reads.py", line 2371, in extending_no_lim
    this_c_seq = next(reads_generator)
  File "/home/raman/anaconda3/bin/get_organelle_from_reads.py", line 2217, in <genexpr>
    reads_generator = (this_read.strip() for this_read in
  File "/home/raman/anaconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/raman/anaconda3/bin/get_organelle_from_reads.py", line 4045, in <module>
    main()
  File "/home/raman/anaconda3/bin/get_organelle_from_reads.py", line 4037, in main
    log_handler = simple_log(log_handler, out_base, prefix=options.prefix + "get_org.")
  File "/home/raman/anaconda3/lib/python3.7/site-packages/GetOrganelleLib/pipe_control_func.py", line 69, in simple_log
    logfile = logging.FileHandler(os.path.join(output_base, prefix + 'log.txt'), mode='a')
  File "/home/raman/anaconda3/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/raman/anaconda3/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
MemoryError

**Comment by Kinggerm** [comment]
It's hitting you machine/environment's memory usage limit, even using --memory-save mode. Please increase the available memory or the word size.

Also keep in mind that given the relative low estimated base coverage, too large word size may risk incompleteness.

**Comment by bioramg** [comment]
Thank you. It's working fine now
