### ISSUE TITLE
(ERR): bowtie2-align exited with value 134

### ISSUE THREAD

**Issue by lstxmu** [Kinggerm/GetOrganelle#87]
Hi, I ran GetOrganelle to assemble a frog mitogenome, however the program failed and getting the following error message:
WORKING DIR: /media/datarun/dgh3samplejob
/home/lst/miniconda3/bin/get_organelle_from_reads.py -1 HLLW_1_clean.fq.gz -2 HLLW_2_clean.fq.gz -o HLLWmtout -F animal_mt -t 12

2021-06-09 14:47:45,729 - INFO: Pre-reading fastq ...
2021-06-09 14:47:45,729 - INFO: Estimating reads to use ... (to use all reads, set '--reduce-reads-for-coverage inf --max-reads inf')
2021-06-09 14:47:45,869 - INFO: Tasting 100000+100000 reads ...
2021-06-09 14:49:19,671 - INFO: Tasting 500000+500000 reads ...
2021-06-09 14:49:56,084 - INFO: Tasting 2500000+2500000 reads ...
2021-06-09 14:52:40,489 - INFO: Estimating reads to use finished.
2021-06-09 14:52:40,490 - INFO: Unzipping reads file: HLLW_1_clean.fq.gz (4141377192 bytes)
2021-06-09 14:58:11,841 - INFO: Unzipping reads file: HLLW_2_clean.fq.gz (4344671592 bytes)
2021-06-09 15:04:16,405 - INFO: Counting read qualities ...
2021-06-09 15:04:16,694 - INFO: Identified quality encoding format = Sanger
2021-06-09 15:04:16,695 - INFO: Phred offset = 33
2021-06-09 15:04:16,697 - INFO: Trimming bases with qualities (0.00%): 33..33  !
2021-06-09 15:04:16,770 - INFO: Mean error rate = 0.0041
2021-06-09 15:04:16,771 - INFO: Counting read lengths ...
2021-06-09 15:08:23,861 - INFO: Mean = 117.5 bp, maximum = 150 bp.
2021-06-09 15:08:23,861 - INFO: Reads used = 59096151+59096151
2021-06-09 15:08:23,862 - INFO: Pre-reading fastq finished.

2021-06-09 15:08:23,862 - INFO: Making seed reads ...
2021-06-09 15:08:23,862 - INFO: Seed bowtie2 index existed!
2021-06-09 15:08:23,863 - INFO: Mapping reads to seed bowtie2 index ...
2021-06-09 15:29:54,367 - ERROR: 
Time loading reference: 00:00:00
Time loading forward index: 00:00:00
Time loading mirror index: 00:00:00
Warning: skipping read 'TTTGGAATCATGCGTCCGGGTTTCAGACTGCCTTCTCTCTCCTGCCTCTGAGTGAGTACACTGAGGCAAATCAGGGTTCTAAGAGCACCCCTTACATCAGGGTTTCCCTTTACACCAGAGTCTTCTCTGTAGATCAGAATTCTCAGTGT' because length (0) <= # seed mismatches (0)
Warning: skipping read 'AATGGGGTTTGGTTTGTAGATGAATGAACGGAATTGTTGTAGGCAAACTCTGCCGATGGCAGCAGAGACACCCAATTGTCTTGAGATGATGAACAAAAACAACGGAGGTATTGCTCCAACGTTTGGTTGGTCCTCTCTGTCTGACCGTT' because length (0) <= # seed mismatches (0)
Warning: skipping read 'AATGGGGTTTGGTTTGTAGATGAATGAACGGAATTGTTGTAGGCAAACTCTGCCGATGGCAGCAGAGACACCCAATTGTCTTGAGATGATGAACAAAAACAACGGAGGTATTGCTCCAACGTTTGGTTGGTCCTCTCTGTCTGACCGTT' because it was < 2 characters long
Warning: skipping read 'TTTGGAATCATGCGTCCGGGTTTCAGACTGCCTTCTCTCTCCTGCCTCTGAGTGAGTACACTGAGGCAAATCAGGGTTCTAAGAGCACCCCTTACATCAGGGTTTCCCTTTACACCAGAGTCTTCTCTGTAGATCAGAATTCTCAGTGT' because it was < 2 characters long
Warning: skipping read 'AGAGGAGGGGGCAGATTCAGTGCGCTCCACTCTGCAGTCTTCACTGTGTGTGTCAGAGGCAGCTGGCGAGGAGAGGTGTCGGTGAGTTGTCATATTCGGCTCCCTATCGCAGACTGCTACAGAAGTCACATGGTGGGCAAATGCGCAAG' because length (0) <= # seed mismatches (0)
Warning: skipping read 'AGAGGAGGGGGCAGATTCAGTGCGCTCCACTCTGCAGTCTTCACTGTGTGTGTCAGAGGCAGCTGGCGAGGAGAGGTGTCGGTGAGTTGTCATATTCGGCTCCCTATCGCAGACTGCTACAGAAGTCACATGGTGGGCAAATGCGCAAG' because it was < 2 characters long
Warning: skipping read 'GCTCATGTAACATTTTTAAGTCACACCAATCATACCTAACCTATGGTATCAGGCTATACATGGATTTAGCCCTCCACTGAGCCCACCCAACCACCAATGAGCTGAACATTACTTACATCCAATTCAAATGTCTGAAGAGCAGTTCTGTA' because length (0) <= # seed mismatches (0)
Error: Encountered one or more spaces while parsing the quality string for read A01045:511:HYKW2DSXY:4:2678:21612:35978 1:N:0:GATAGTCG+GTCCACATWarning: skipping read 'TACAGAGAGGACTCTGATGTAAAGGGCAGCACTGTGGTCTCTGATGTAAAGGGGAGCTCTGATGTATCTTATCTTAGCGTACTTACTTAGAGGCAGGAGAGAGAAGGGGGAGGGGTAGACTTAGTCCGGTTTGAATAATGTGTCCGGGT' because length (0) <= # seed mismatches (0)
Warning: skipping read 'CTCCGCAGGCGGCAATCCCAGGTCCTCCAACTGAAGCCGTTGGGCAAATTCGGTCTTGGCGAAGACCCCACCGTCCGACATCCGCCCATTTTTCCCAACATCCAGGTAGAGAAACTCGTAGTTGGCAGACACCACCGCCATCAGAACAA' because length (0) <= # seed mismatches (0)
Warning: skipping read 'GCCTCCTCCTCCGCCCTCGTCTCGTCTGGCGTCCTCCTCCTCCCTCGTCTCGTCTGGCCTCCTCCTCCTCCACCCTCGGGTCGGCAGGCCGAAAGGGAGCTCAGACCGAAGGACGCCAGACACGGACGTCGAGAGGGGATGCCGGGTGA' because length (0) <= # seed mismatches (0)
Warning: skipping read 'TACAGAGAGGACTCTGATGTAAAGGGCAGCACTGTGGTCTCTGATGTAAAGGGGAGCTCTGATGTATCTTATCTTAGCGTACTTACTTAGAGGCAGGAGAGAGAAGGGGGAGGGGTAGACTTAGTCCGGTTTGAATAATGTGTCCGGGT' because it was < 2 characters long
.  If this is a FASTQ file Warning: skipping read 'ACAGACAGGGTCCCAGCAGGCTGCCAGGCAGGCTCCCTCCACCCCTCCAGGGACTCATCAGGCTTCCCCCGGCTTGCCTGATCCCCGCTGGCTTCCTCCTTCATCCCTTCGCCAGGGAGCCAAGCAGGTAAGCCACCCACCGGGACTGC' because length (0) <= # seed mismatches (0)
Warning: skipping read 'CGAATCCCAAACATCCAACAACGGCTCTGAAACAGCCGCGTACAAACGCCCGGGTCTTCCTCATGTTGGGGGGGCTTTTTGGGGGTATCTGCAGGCTGGTCACTGATACCTCCTTCCATAGCTGCCCTTCCTTTGCTGCCTTTCTCTTT' because length (0) <= # seed mismatches (0)
Warning: skipping read 'GCTCATGTAACATTTTTAAGTCACACCAATCATACCTAACCTATGGTATCAGGCTATACATGGATTTAGCCCTCCACTGAGCCCACCCAACCACCAATGAGCTGAACATTACTTACATCCAATTCAAATGTCTGAAGAGCAGTTCTGTA' because it was < 2 characters long

Aborted (core dumped)
Argument "A01045:511:HYKW2DSXY:4:2678:643" isn't numeric in bitwise and (&) at /home/lst/miniconda3/bin/bowtie2 line 575, <BT> line 92377570.
Use of uninitialized value $l in scalar chomp at /home/lst/miniconda3/bin/bowtie2 line 588, <BT> line 92377570.
Use of uninitialized value $l in substitution (s///) at /home/lst/miniconda3/bin/bowtie2 line 589, <BT> line 92377570.
Use of uninitialized value $l in print at /home/lst/miniconda3/bin/bowtie2 line 596, <BT> line 92377570.
(ERR): bowtie2-align exited with value 134

2021-06-09 15:29:54,368 - ERROR: 
Traceback (most recent call last):
  File "/home/lst/miniconda3/bin/get_organelle_from_reads.py", line 3935, in main
    seed_fq, seed_sam, new_seed_f = making_seed_reads_using_mapping(
  File "/home/lst/miniconda3/bin/get_organelle_from_reads.py", line 3037, in making_seed_reads_using_mapping
    map_with_bowtie2(seed_file=seed_file, original_fq_files=original_fq_files,
  File "/home/lst/miniconda3/lib/python3.9/site-packages/GetOrganelleLib/pipe_control_func.py", line 398, in map_with_bowtie2
    raise Exception("")
Exception

=================================
Please help me to fix this issue.

Thank you!
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/6622653/get_org.log.txt)

**Comment by Kinggerm** [comment]
It may be related to this FAQ: https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#err-bowtie2-align-died-with-signal-6-abrt-core-dumped

Let me know your update.

**Comment by Kinggerm** [comment]
I will close this issue if there's no further followups, feel free to reopen it if the error still persists
